<?php
/**
 * Title: The Bar Collection
 * Slug: meteora/bar-collection
 * Categories: meteora-sections
 * Description: Interactive bar index with crossfading images (rail on mobile).
 * Viewport Width: 1440
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:group {"tagName":"section","metadata":{"name":"The Bar Collection"},"align":"full","className":"mt-section mt-bars","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-bars" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dsplit","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--split"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'The Bar Collection', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'The bar <em>collection.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"><?php echo esc_html__( 'Modular, scenographic bars, each in three sizes — Slim 1.5 m, Medium 3.5 m, Large 5.5 m. A collection that keeps growing.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Bar collection"},"className":"mt-bc","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bc"><!-- wp:group {"className":"mt-bar","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-bar__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-bar__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-mirror-sunset.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Golden Mirror bar at sunset on a terrace overlooking the hills', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-bar__body","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__body"><!-- wp:paragraph {"className":"is-style-micro mt-bar__n"} -->
<p class="is-style-micro mt-bar__n"><span class="mt-bar__num">01</span></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-bar__name"} -->
<h3 class="wp-block-heading mt-bar__name"><a href="<?php echo esc_url( meteora_page_url( 'bar-golden-mirror' ) ); ?>">Golden Mirror</a></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bar__mood"} -->
<p class="mt-bar__mood"><?php echo esc_html__( 'Scenic impact, strong character.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__desc is-muted"} -->
<p class="mt-bar__desc is-muted"><?php echo esc_html__( 'Its mirrored gold surface reflects light and atmosphere, turning the bar into the focal point of the event.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__ideal"} -->
<p class="mt-bar__ideal"><?php echo wp_kses_post( __( '<span class="mt-bar__ideal-label">Ideal for</span> Glamorous receptions · Exclusive parties · Settings built for visual impact', 'meteora' ) ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-bar__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-bar__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/silver-reflection.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Silver Reflection bar in a large hall set for a gala dinner', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-bar__body","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__body"><!-- wp:paragraph {"className":"is-style-micro mt-bar__n"} -->
<p class="is-style-micro mt-bar__n"><span class="mt-bar__num">02</span></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-bar__name"} -->
<h3 class="wp-block-heading mt-bar__name"><a href="<?php echo esc_url( meteora_page_url( 'bar-silver-reflection' ) ); ?>">Silver Reflection</a></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bar__mood"} -->
<p class="mt-bar__mood"><?php echo esc_html__( 'Modern, brilliant, sophisticated.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__desc is-muted"} -->
<p class="mt-bar__desc is-muted"><?php echo esc_html__( 'Mirrored silver brings contemporary elegance and makes the most of the ambient lighting.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__ideal"} -->
<p class="mt-bar__ideal"><?php echo wp_kses_post( __( '<span class="mt-bar__ideal-label">Ideal for</span> Corporate events · Chic weddings · Minimalist design setups', 'meteora' ) ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-bar__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-bar__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/pure-white-villa.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Pure White bar in the garden of a stone villa at sunset', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-bar__body","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__body"><!-- wp:paragraph {"className":"is-style-micro mt-bar__n"} -->
<p class="is-style-micro mt-bar__n"><span class="mt-bar__num">03</span></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-bar__name"} -->
<h3 class="wp-block-heading mt-bar__name"><a href="<?php echo esc_url( meteora_page_url( 'bar-pure-white' ) ); ?>">Pure White</a></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bar__mood"} -->
<p class="mt-bar__mood"><?php echo esc_html__( 'Luminous elegance, refined texture.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__desc is-muted"} -->
<p class="mt-bar__desc is-muted"><?php echo esc_html__( 'Glossy white with a herringbone pattern creates movement and depth while keeping a clean, contemporary look.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__ideal"} -->
<p class="mt-bar__ideal"><?php echo wp_kses_post( __( '<span class="mt-bar__ideal-label">Ideal for</span> Elegant weddings · Minimalist luxury events · Sophisticated settings', 'meteora' ) ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar is-soon","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar is-soon"><!-- wp:group {"className":"mt-bar__media mt-swatch","style":{"color":{"background":"#a9b49a"}},"layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__media mt-swatch has-background" style="background-color:#a9b49a"><!-- wp:paragraph {"className":"mt-swatch__label"} -->
<p class="mt-swatch__label"><?php echo esc_html__( 'Coming soon', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar__body","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__body"><!-- wp:paragraph {"className":"is-style-micro mt-bar__n"} -->
<p class="is-style-micro mt-bar__n"><span class="mt-bar__num">04</span><span class="mt-bar__soon"><?php echo esc_html__( 'Coming soon', 'meteora' ); ?></span></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-bar__name"} -->
<h3 class="wp-block-heading mt-bar__name">Green Harmony</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bar__mood"} -->
<p class="mt-bar__mood"><?php echo esc_html__( 'Natural freshness.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__desc is-muted"} -->
<p class="mt-bar__desc is-muted"><?php echo esc_html__( 'Fresh, luminous, contemporary. The light-green finish adds an elegant botanical touch.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__ideal"} -->
<p class="mt-bar__ideal"><?php echo wp_kses_post( __( '<span class="mt-bar__ideal-label">Ideal for</span> Garden parties · Modern weddings · Eco-chic events', 'meteora' ) ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar is-soon","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar is-soon"><!-- wp:group {"className":"mt-bar__media mt-swatch","style":{"color":{"background":"#8a6a4c"}},"layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__media mt-swatch has-background" style="background-color:#8a6a4c"><!-- wp:paragraph {"className":"mt-swatch__label"} -->
<p class="mt-swatch__label"><?php echo esc_html__( 'Coming soon', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar__body","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__body"><!-- wp:paragraph {"className":"is-style-micro mt-bar__n"} -->
<p class="is-style-micro mt-bar__n"><span class="mt-bar__num">05</span><span class="mt-bar__soon"><?php echo esc_html__( 'Coming soon', 'meteora' ); ?></span></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-bar__name"} -->
<h3 class="wp-block-heading mt-bar__name">Country Classic</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bar__mood"} -->
<p class="mt-bar__mood"><?php echo esc_html__( 'Warm, natural, cosy.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__desc is-muted"} -->
<p class="mt-bar__desc is-muted"><?php echo esc_html__( 'Exposed-grain wood creates an authentic country-chic atmosphere.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__ideal"} -->
<p class="mt-bar__ideal"><?php echo wp_kses_post( __( '<span class="mt-bar__ideal-label">Ideal for</span> Outdoor events · Boho-style weddings', 'meteora' ) ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar is-soon","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar is-soon"><!-- wp:group {"className":"mt-bar__media mt-swatch","style":{"color":{"background":"#1c1614"}},"layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__media mt-swatch has-background" style="background-color:#1c1614"><!-- wp:paragraph {"className":"mt-swatch__label"} -->
<p class="mt-swatch__label"><?php echo esc_html__( 'Coming soon', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar__body","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__body"><!-- wp:paragraph {"className":"is-style-micro mt-bar__n"} -->
<p class="is-style-micro mt-bar__n"><span class="mt-bar__num">06</span><span class="mt-bar__soon"><?php echo esc_html__( 'Coming soon', 'meteora' ); ?></span></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-bar__name"} -->
<h3 class="wp-block-heading mt-bar__name">Black Essence</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bar__mood"} -->
<p class="mt-bar__mood"><?php echo esc_html__( 'Lacquered black, pure and sophisticated.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__desc is-muted"} -->
<p class="mt-bar__desc is-muted"><?php echo esc_html__( 'A bold, contemporary character that makes the bar a scenographic element of great impact.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__ideal"} -->
<p class="mt-bar__ideal"><?php echo wp_kses_post( __( '<span class="mt-bar__ideal-label">Ideal for</span> Luxury events · Gala nights · Exclusive parties · Modern minimalist weddings', 'meteora' ) ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:buttons {"className":"mt-cta-row mt-section-cta"} -->
<div class="wp-block-buttons mt-cta-row mt-section-cta"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'bars' ) ); ?>"><?php echo esc_html__( 'Explore the collection', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link meteora-track-bars_quote"} -->
<div class="wp-block-button is-style-button-text-link meteora-track-bars_quote"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></section>
<!-- /wp:group -->
