<?php
/**
 * Title: Cocktail families
 * Slug: meteora/cocktail-families
 * Categories: meteora-sections
 * Description: Seven cocktail families with an arched crossfading frame.
 * Viewport Width: 1440
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:group {"tagName":"section","metadata":{"name":"Cocktail experience"},"align":"full","className":"mt-section mt-home-cocktails is-style-section-alt","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-home-cocktails is-style-section-alt" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dsplit","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--split"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up">Cocktail Experience</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Where cocktails <em>become part of the event.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"><?php echo esc_html__( 'A complete, balanced drink list, from the great classics to the Italian aperitivo, with variations on request and signatures created for you.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Cocktail families"},"className":"mt-cf","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cf"><!-- wp:group {"className":"mt-cf__frame","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cf__frame"></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cf__list","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cf__list"><!-- wp:group {"className":"mt-cf__row","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cf__row"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cf__img"} -->
<figure class="wp-block-image size-large mt-cf__img"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/old-fashioned.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Old Fashioned', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"mt-cf__name"} -->
<p class="mt-cf__name"><a href="<?php echo esc_url( meteora_page_url( 'cocktails', 'classics' ) ); ?>"><?php echo esc_html__( 'Classics', 'meteora' ); ?></a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-cf__blurb"} -->
<p class="mt-cf__blurb"><?php echo esc_html__( 'The great recipes, executed with method.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-micro mt-cf__drink"} -->
<p class="is-style-micro mt-cf__drink">Old Fashioned</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cf__row","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cf__row"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cf__img"} -->
<figure class="wp-block-image size-large mt-cf__img"><img src="<?php echo esc_url( meteora_asset( 'assets/images/details/ice-stamp.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Ice cube pressed with initials', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"mt-cf__name"} -->
<p class="mt-cf__name"><a href="<?php echo esc_url( meteora_page_url( 'cocktails', 'signature' ) ); ?>"><?php echo esc_html__( 'Signatures', 'meteora' ); ?></a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-cf__blurb"} -->
<p class="mt-cf__blurb"><?php echo esc_html__( 'Drinks created and named after your story or your brand identity.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cf__row","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cf__row"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cf__img"} -->
<figure class="wp-block-image size-large mt-cf__img"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/spritz.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Spritz', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"mt-cf__name"} -->
<p class="mt-cf__name"><a href="<?php echo esc_url( meteora_page_url( 'cocktails', 'spritz' ) ); ?>"><?php echo esc_html__( 'Spritz', 'meteora' ); ?></a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-cf__blurb"} -->
<p class="mt-cf__blurb"><?php echo esc_html__( 'Aperol, Campari, Hugo, Limoncello, Passion Fruit.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-micro mt-cf__drink"} -->
<p class="is-style-micro mt-cf__drink">Spritz</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cf__row","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cf__row"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cf__img"} -->
<figure class="wp-block-image size-large mt-cf__img"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/espresso-martini.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Espresso Martini', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"mt-cf__name"} -->
<p class="mt-cf__name"><a href="<?php echo esc_url( meteora_page_url( 'cocktails', 'martini' ) ); ?>"><?php echo esc_html__( 'Martini', 'meteora' ); ?></a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-cf__blurb"} -->
<p class="mt-cf__blurb"><?php echo esc_html__( 'Chilled coupes, clean lines.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-micro mt-cf__drink"} -->
<p class="is-style-micro mt-cf__drink">Espresso Martini</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cf__row","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cf__row"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cf__img"} -->
<figure class="wp-block-image size-large mt-cf__img"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/sour.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Whiskey · Vodka · Gin · Tequila Sour', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"mt-cf__name"} -->
<p class="mt-cf__name"><a href="<?php echo esc_url( meteora_page_url( 'cocktails', 'sour' ) ); ?>"><?php echo esc_html__( 'Sour', 'meteora' ); ?></a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-cf__blurb"} -->
<p class="mt-cf__blurb"><?php echo esc_html__( 'Balance between citrus, sweetness and structure.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-micro mt-cf__drink"} -->
<p class="is-style-micro mt-cf__drink">Whiskey · Vodka · Gin · Tequila Sour</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cf__row","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cf__row"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cf__img"} -->
<figure class="wp-block-image size-large mt-cf__img"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/mojito.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Mojito', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"mt-cf__name"} -->
<p class="mt-cf__name"><a href="<?php echo esc_url( meteora_page_url( 'cocktails', 'tropical' ) ); ?>"><?php echo esc_html__( 'Tropical', 'meteora' ); ?></a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-cf__blurb"} -->
<p class="mt-cf__blurb"><?php echo esc_html__( 'Fresh, lively, made for the party.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-micro mt-cf__drink"} -->
<p class="is-style-micro mt-cf__drink">Mojito</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cf__row","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cf__row"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cf__img"} -->
<figure class="wp-block-image size-large mt-cf__img"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/negroni.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Negroni', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"mt-cf__name"} -->
<p class="mt-cf__name"><a href="<?php echo esc_url( meteora_page_url( 'cocktails', 'aperitivo' ) ); ?>"><?php echo esc_html__( 'Italian aperitivo', 'meteora' ); ?></a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-cf__blurb"} -->
<p class="mt-cf__blurb"><?php echo esc_html__( 'The Italian ritual, from Negroni to Bellini.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-micro mt-cf__drink"} -->
<p class="is-style-micro mt-cf__drink">Negroni</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
