<?php
/**
 * Title: Essential vs Premium
 * Slug: meteora/comparison
 * Categories: meteora-sections
 * Description: Refined comparison, no prices.
 * Viewport Width: 1440
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:group {"tagName":"section","metadata":{"name":"Essential vs Premium"},"align":"full","className":"mt-section mt-compare","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-compare" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dsplit","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--split"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up">Open Bar</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Two experiences, <em>one standard.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Essential vs Premium"},"className":"mt-cmp","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cmp"><!-- wp:table {"hasFixedLayout":false,"className":"mt-cmp__table"} -->
<figure class="wp-block-table mt-cmp__table"><table><thead><tr><th></th><th><?php echo wp_kses_post( __( '<span>Open Bar</span> Essential <em>Experience</em>', 'meteora' ) ); ?></th><th><?php echo wp_kses_post( __( '<span>Open Bar</span> Premium <em>Experience</em>', 'meteora' ) ); ?></th></tr></thead><tbody><tr><td><?php echo esc_html__( 'Spirits', 'meteora' ); ?></td><td><?php echo esc_html__( 'Reliable labels from established international houses, chosen for balance and consistency.', 'meteora' ); ?></td><td><?php echo esc_html__( 'Premium labels such as Grey Goose, Belvedere, Hendrick’s, Tanqueray No. Ten, Patrón and Diplomático.', 'meteora' ); ?></td></tr><tr><td><?php echo esc_html__( 'Mixers and soft drinks', 'meteora' ); ?></td><td><?php echo esc_html__( 'Tonics, soda and soft drinks in professional service formats.', 'meteora' ); ?></td><td><?php echo esc_html__( 'Fever-Tree tonics, soft drinks and San Pellegrino water, all in glass.', 'meteora' ); ?></td></tr><tr><td><?php echo esc_html__( 'Presentation', 'meteora' ); ?></td><td><?php echo esc_html__( 'Bar of your choice, professional glassware, fresh and dehydrated fruit, botanicals and spices.', 'meteora' ); ?></td><td><?php echo esc_html__( 'Everything in Essential, with glass bottles on display that elevate the look of the bar.', 'meteora' ); ?></td></tr><tr><td><?php echo esc_html__( 'Experience', 'meteora' ); ?></td><td><?php echo esc_html__( 'A complete, polished open bar, managed with full autonomy.', 'meteora' ); ?></td><td><?php echo esc_html__( 'For hosts who want every drink to speak the language of the great labels.', 'meteora' ); ?></td></tr></tbody></table><figcaption class="wp-element-caption"><?php echo esc_html__( 'Essential and Premium Experience compared', 'meteora' ); ?></figcaption></figure>
<!-- /wp:table -->

<!-- wp:paragraph {"className":"is-muted mt-cmp__note"} -->
<p class="is-muted mt-cmp__note"><?php echo esc_html__( 'Labels may vary with availability, replaced by equivalent or superior references and always communicated in advance. Requests for other brands are welcome.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-muted mt-cmp__note"} -->
<p class="is-muted mt-cmp__note"><?php echo esc_html__( 'Both formulas include three hours of open bar, a bar of your choice, our signature drink list, professional staff and our own glassware. Extra time, additional staff and extra bar modules on request.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"has-arrow meteora-track-comparison_quote"} -->
<div class="wp-block-button has-arrow meteora-track-comparison_quote"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
