<?php
/**
 * Title: Destination weddings in Italy
 * Slug: meteora/destinations
 * Categories: meteora-sections
 * Description: Sticky intro with the list of destinations.
 * Viewport Width: 1440
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:group {"tagName":"section","metadata":{"name":"Destination weddings"},"align":"full","className":"mt-section mt-home-dest is-style-section-alt","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-home-dest is-style-section-alt" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-split mt-split\u002d\u002dsticky","layout":{"type":"default"}} -->
<div class="wp-block-group mt-split mt-split--sticky"><!-- wp:group {"className":"mt-split__intro","layout":{"type":"default"}} -->
<div class="wp-block-group mt-split__intro"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up">Destination Weddings</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Destination weddings <em>in Italy.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead is-muted animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted animate-fade-up animate-delay-2"><?php echo esc_html__( 'Based in Tuscany, available throughout Italy. For couples who choose Italy, we are the bar partner who knows the villas, the timings and the people.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'destination' ) ); ?>"><?php echo esc_html__( 'Destination weddings with Meteora', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest mt-dest\u002d\u002dcompact","layout":{"type":"default"}} -->
<div class="wp-block-group mt-dest mt-dest--compact"><!-- wp:group {"className":"mt-dest__row animate-fade-up has-link","layout":{"type":"default"},"anchor":"dest-tuscany"} -->
<div id="dest-tuscany" class="wp-block-group mt-dest__row animate-fade-up has-link"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><a href="<?php echo esc_url( meteora_page_url( 'tuscany' ) ); ?>"><?php echo esc_html__( 'Tuscany', 'meteora' ); ?></a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Our home base. Villas, hamlets and farmhouses where we work with the ease of locals.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-florence"} -->
<div id="dest-florence" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'Florence', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Historic palazzi, rooftop terraces and villas on the Florentine hills.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-chianti"} -->
<div id="dest-chianti" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'Chianti', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Wine estates and farmhouses among the vines, for open-air receptions.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-siena"} -->
<div id="dest-siena" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'Siena', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Medieval hamlets and country estates around Siena and the Val d’Orcia.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-lucca"} -->
<div id="dest-lucca" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'Lucca', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Lucchese villas and historic gardens, minutes from our base.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-pisa"} -->
<div id="dest-pisa" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'Pisa', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Between art city, countryside and coast.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-forte-dei-marmi"} -->
<div id="dest-forte-dei-marmi" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'Forte dei Marmi', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Seaside events on the Versilia coast, from sunset until late.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-italy"} -->
<div id="dest-italy" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'All of Italy and abroad', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'We travel throughout Italy and also deliver services outside the region and abroad.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
