<?php
/**
 * Title: Editorial — image + text (weddings)
 * Slug: meteora/editorial-weddings
 * Categories: meteora-sections
 * Description: Asymmetric image pair with text and CTAs.
 * Viewport Width: 1440
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:group {"tagName":"section","metadata":{"name":"Weddings"},"align":"full","className":"mt-section mt-home-weddings","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-home-weddings" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-ed mt-ed\u002d\u002dlandscape mt-ed\u002d\u002dpair","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ed mt-ed--landscape mt-ed--pair"><!-- wp:group {"className":"mt-ed__figure","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ed__figure"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ed__main animate-image-reveal animate-drift"} -->
<figure class="wp-block-image size-large mt-ed__main animate-image-reveal animate-drift"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/pure-white-villa.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Pure White bar in the garden of a stone villa', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ed__second animate-image-reveal animate-delay-2"} -->
<figure class="wp-block-image size-large mt-ed__second animate-image-reveal animate-delay-2"><img src="<?php echo esc_url( meteora_asset( 'assets/images/details/mint-coupes.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Coupes with fresh mint and red berries on the bar', 'meteora' ); ?>"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ed__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ed__text"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'Weddings', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Your wedding. <em>Your bar experience.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead is-muted animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted animate-fade-up animate-delay-2"><?php echo esc_html__( 'From the garden aperitivo to the last toast after dinner, the bar accompanies every moment of the day — and stays in the photographs.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:list {"className":"is-style-list-inline animate-fade-up animate-delay-3"} -->
<ul class="wp-block-list is-style-list-inline animate-fade-up animate-delay-3"><!-- wp:list-item -->
<li><?php echo esc_html__( 'Aperitivo', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Open bar', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Cocktails', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Signature moments', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Towers', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Customisation', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Service', 'meteora' ); ?></li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:buttons {"className":"mt-cta-row animate-fade-up animate-delay-4"} -->
<div class="wp-block-buttons mt-cta-row animate-fade-up animate-delay-4"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'weddings' ) ); ?>"><?php echo esc_html__( 'Discover wedding services', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link meteora-track-weddings_quote"} -->
<div class="wp-block-button is-style-button-text-link meteora-track-weddings_quote"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
