<?php
/**
 * Title: Not just an open bar
 * Slug: meteora/experience-mosaic
 * Categories: meteora-sections
 * Description: Dark editorial mosaic: bar, cocktails, staff, glassware, ice, details, logistics.
 * Viewport Width: 1440
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:group {"tagName":"section","metadata":{"name":"Not just an open bar"},"align":"full","className":"mt-section mt-experience is-style-section-dark","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"},"anchor":"experience"} -->
<section class="wp-block-group alignfull mt-section mt-experience is-style-section-dark" id="experience" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dsplit","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--split"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'Meteora Experience', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1","anchor":"experience-title"} -->
<h2 id="experience-title" class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Not just <em>an open bar.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"><?php echo esc_html__( 'We design and run the entire beverage experience of your event: from the bar to the ice, from glassware to staff, from setup to the last drink. You think about your guests.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-mosaic","layout":{"type":"default"}} -->
<div class="wp-block-group mt-mosaic"><!-- wp:group {"className":"mt-mosaic__item animate-fade-up animate-delay-1","layout":{"type":"default"}} -->
<div class="wp-block-group mt-mosaic__item animate-fade-up animate-delay-1"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-mosaic__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-mosaic__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-marble-night.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Golden bar on a chevron floor', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"is-style-micro mt-mosaic__n"} -->
<p class="is-style-micro mt-mosaic__n">01</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-mosaic__name"} -->
<h3 class="wp-block-heading mt-mosaic__name"><?php echo esc_html__( 'The bar', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-mosaic__d"} -->
<p class="mt-mosaic__d"><?php echo esc_html__( 'Scenographic, modular, in three sizes.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-mosaic__item animate-fade-up animate-delay-2","layout":{"type":"default"}} -->
<div class="wp-block-group mt-mosaic__item animate-fade-up animate-delay-2"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-mosaic__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-mosaic__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/espresso-martini.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Espresso Martini', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"is-style-micro mt-mosaic__n"} -->
<p class="is-style-micro mt-mosaic__n">02</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-mosaic__name"} -->
<h3 class="wp-block-heading mt-mosaic__name"><?php echo esc_html__( 'Cocktails', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-mosaic__d"} -->
<p class="mt-mosaic__d"><?php echo esc_html__( 'Classics made with method, bespoke signatures.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-mosaic__item animate-fade-up animate-delay-3","layout":{"type":"default"}} -->
<div class="wp-block-group mt-mosaic__item animate-fade-up animate-delay-3"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-mosaic__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-mosaic__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/team/bartender-strain.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Bartender in black uniform straining a cocktail', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"is-style-micro mt-mosaic__n"} -->
<p class="is-style-micro mt-mosaic__n">03</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-mosaic__name"} -->
<h3 class="wp-block-heading mt-mosaic__name"><?php echo esc_html__( 'Staff', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-mosaic__d"} -->
<p class="mt-mosaic__d"><?php echo esc_html__( 'Total black, discreet, professional.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-mosaic__item animate-fade-up animate-delay-1","layout":{"type":"default"}} -->
<div class="wp-block-group mt-mosaic__item animate-fade-up animate-delay-1"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-mosaic__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-mosaic__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/details/champagne-bowl.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Champagne bowl and back bar', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"is-style-micro mt-mosaic__n"} -->
<p class="is-style-micro mt-mosaic__n">04</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-mosaic__name"} -->
<h3 class="wp-block-heading mt-mosaic__name"><?php echo esc_html__( 'Glassware', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-mosaic__d"} -->
<p class="mt-mosaic__d"><?php echo esc_html__( 'The right glass for every drink.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-mosaic__item animate-fade-up animate-delay-2","layout":{"type":"default"}} -->
<div class="wp-block-group mt-mosaic__item animate-fade-up animate-delay-2"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-mosaic__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-mosaic__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/ice/cube-5cm.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Clear 5×5 cm ice cube held in a hand', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"is-style-micro mt-mosaic__n"} -->
<p class="is-style-micro mt-mosaic__n">05</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-mosaic__name"} -->
<h3 class="wp-block-heading mt-mosaic__name"><?php echo esc_html__( 'Ice', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-mosaic__d"} -->
<p class="mt-mosaic__d"><?php echo esc_html__( 'An integral part of the cocktail.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-mosaic__item animate-fade-up animate-delay-3","layout":{"type":"default"}} -->
<div class="wp-block-group mt-mosaic__item animate-fade-up animate-delay-3"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-mosaic__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-mosaic__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/details/mint-coupes.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Coupes with fresh mint and red berries', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"is-style-micro mt-mosaic__n"} -->
<p class="is-style-micro mt-mosaic__n">06</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-mosaic__name"} -->
<h3 class="wp-block-heading mt-mosaic__name"><?php echo esc_html__( 'Details', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-mosaic__d"} -->
<p class="mt-mosaic__d"><?php echo esc_html__( 'Fruit, botanicals, garnish.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-mosaic__item animate-fade-up animate-delay-1","layout":{"type":"default"}} -->
<div class="wp-block-group mt-mosaic__item animate-fade-up animate-delay-1"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-mosaic__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-mosaic__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/terrace-panorama.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Bar set up in front of a panoramic window', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"is-style-micro mt-mosaic__n"} -->
<p class="is-style-micro mt-mosaic__n">07</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-mosaic__name"} -->
<h3 class="wp-block-heading mt-mosaic__name"><?php echo esc_html__( 'Logistics', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-mosaic__d"} -->
<p class="mt-mosaic__d"><?php echo esc_html__( 'Independent from setup to load-out.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:buttons {"className":"mt-cta-row mt-section-cta"} -->
<div class="wp-block-buttons mt-cta-row mt-section-cta"><!-- wp:button {"className":"is-style-button-light"} -->
<div class="wp-block-button is-style-button-light"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'cocktails' ) ); ?>"><?php echo esc_html__( 'Discover the cocktail experience', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link meteora-track-experience_quote"} -->
<div class="wp-block-button is-style-button-text-link meteora-track-experience_quote"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></section>
<!-- /wp:group -->
