<?php
/**
 * Title: Hero — dark landing
 * Slug: meteora/hero-page-dark
 * Categories: meteora-sections, banner
 * Description: Tall dark photo hero with breadcrumbs (Destination, Corporate).
 * Viewport Width: 1440
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:cover {"url":"<?php echo esc_url( meteora_asset( 'assets/images/bars/silver-reflection.webp' ) ); ?>","alt":"<?php echo esc_attr__( 'Silver Reflection bar in a large hall', 'meteora' ); ?>","minHeight":88,"minHeightUnit":"svh","gradient":"hero-shade","contentPosition":"bottom left","tagName":"section","align":"full","className":"mt-hero mt-hero\u002d\u002dtall animate-hero-settle","layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-cover alignfull has-custom-content-position is-position-bottom-left mt-hero mt-hero--tall animate-hero-settle" style="min-height:88svh"><img class="wp-block-cover__image-background" alt="<?php echo esc_attr__( 'Silver Reflection bar in a large hall', 'meteora' ); ?>" src="<?php echo esc_url( meteora_asset( 'assets/images/bars/silver-reflection.webp' ) ); ?>" data-object-fit="cover"/><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim wp-block-cover__gradient-background has-background-gradient has-hero-shade-gradient-background"></span><div class="wp-block-cover__inner-container"><!-- wp:breadcrumbs {"className":"mt-crumbs"} /-->

<!-- wp:paragraph {"className":"is-style-eyebrow"} -->
<p class="is-style-eyebrow"><?php echo esc_html__( 'Corporate & private events', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":1,"className":"mt-hero__title mt-hero__title\u002d\u002dpage"} -->
<h1 class="wp-block-heading mt-hero__title mt-hero__title--page"><?php echo wp_kses_post( __( 'Your brand, <em>served with style.</em>', 'meteora' ) ); ?></h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead mt-hero__lead"} -->
<p class="is-style-lead mt-hero__lead"><?php echo esc_html__( 'Professionalism, customisation and discretion for corporate events, launches, activations and private parties.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"className":"mt-cta-row"} -->
<div class="wp-block-buttons mt-cta-row"><!-- wp:button {"className":"is-style-button-light meteora-track-hero_quote"} -->
<div class="wp-block-button is-style-button-light meteora-track-hero_quote"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></section>
<!-- /wp:cover -->
