<?php
/**
 * Title: Hero — cinematic home
 * Slug: meteora/hero-home
 * Categories: meteora-sections, banner
 * Description: Full-screen photo hero with headline, lead and two CTAs.
 * Viewport Width: 1440
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:cover {"url":"<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-mirror-sunset.webp' ) ); ?>","alt":"<?php echo esc_attr__( 'Golden Mirror bar at sunset on a terrace overlooking the hills', 'meteora' ); ?>","focalPoint":{"x":0.5,"y":0.6},"minHeight":100,"minHeightUnit":"svh","gradient":"hero-shade","contentPosition":"bottom left","tagName":"section","align":"full","className":"mt-hero animate-hero-settle","layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-cover alignfull has-custom-content-position is-position-bottom-left mt-hero animate-hero-settle" style="min-height:100svh"><img class="wp-block-cover__image-background" alt="<?php echo esc_attr__( 'Golden Mirror bar at sunset on a terrace overlooking the hills', 'meteora' ); ?>" src="<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-mirror-sunset.webp' ) ); ?>" style="object-position:50% 60%" data-object-fit="cover" data-object-position="50% 60%"/><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim wp-block-cover__gradient-background has-background-gradient has-hero-shade-gradient-background"></span><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"className":"is-style-eyebrow"} -->
<p class="is-style-eyebrow"><?php echo esc_html__( 'Weddings · Destination weddings · Corporate · Private', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":1,"className":"mt-hero__title"} -->
<h1 class="wp-block-heading mt-hero__title"><?php echo wp_kses_post( __( 'Luxury Open Bar Catering <em>&amp; Hospitality Services</em>', 'meteora' ) ); ?></h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead mt-hero__lead"} -->
<p class="is-style-lead mt-hero__lead"><?php echo esc_html__( 'Premium bar catering for weddings, destination weddings, corporate and private events. Based in Tuscany, throughout Italy.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"className":"mt-cta-row"} -->
<div class="wp-block-buttons mt-cta-row"><!-- wp:button {"className":"is-style-button-light has-arrow meteora-track-hero_quote"} -->
<div class="wp-block-button is-style-button-light has-arrow meteora-track-hero_quote"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-ghost-light meteora-track-hero_explore"} -->
<div class="wp-block-button is-style-button-ghost-light meteora-track-hero_explore"><a class="wp-block-button__link wp-element-button" href="#experience"><?php echo esc_html__( 'Explore the experience', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></section>
<!-- /wp:cover -->
