<?php
/**
 * Title: Ice is part of the cocktail
 * Slug: meteora/ice
 * Categories: meteora-sections
 * Description: Dark section: five principles and the ice formats.
 * Viewport Width: 1440
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:group {"tagName":"section","metadata":{"name":"Ice"},"align":"full","className":"mt-section mt-ice is-style-section-dark","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"},"anchor":"ice"} -->
<section class="wp-block-group alignfull mt-section mt-ice is-style-section-dark" id="ice" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-ice__grid","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__grid"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ice__media animate-image-reveal animate-drift"} -->
<figure class="wp-block-image size-large mt-ice__media animate-image-reveal animate-drift"><img src="<?php echo esc_url( meteora_asset( 'assets/images/ice/pour-coupe.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Crushed ice falling into a cocktail coupe', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-ice__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__text"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'The ice we use', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"is-style-display mt-ice__title animate-fade-up animate-delay-1","anchor":"ice-title"} -->
<h2 id="ice-title" class="wp-block-heading is-style-display mt-ice__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Ice is <em>part of the cocktail.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-ice__principles","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__principles"><!-- wp:group {"className":"mt-ice__principle animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__principle animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro"} -->
<p class="is-style-micro">01</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Temperature', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Ice does not only chill: it brings the drink to the right temperature and holds it there.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__principle animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__principle animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro"} -->
<p class="is-style-micro">02</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Dilution', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Too much ice flattens a cocktail; too little makes it aggressive.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__principle animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__principle animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro"} -->
<p class="is-style-micro">03</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Texture', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'The smaller the ice, the faster it chills. The larger and denser, the more dilution is controlled over time.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__principle animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__principle animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro"} -->
<p class="is-style-micro">04</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Presentation', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'A clear cube, a sphere, a tall long-drink spear: ice is seen, and it speaks.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__principle animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__principle animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro"} -->
<p class="is-style-micro">05</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Precision', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Every cocktail has its own rules. Every cocktail begins with a precise choice.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__rail","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__rail"><!-- wp:group {"className":"mt-ice__type animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__type animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ice__thumb"} -->
<figure class="wp-block-image size-large mt-ice__thumb"><img src="<?php echo esc_url( meteora_asset( 'assets/images/ice/compact-cube.webp' ) ); ?>" alt="<?php echo esc_attr__( 'High-density compact cube', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-ice__name"} -->
<h3 class="wp-block-heading mt-ice__name"><?php echo esc_html__( 'High-density compact cube', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Slow melting, controlled dilution in long drinks and structured cocktails.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__type animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__type animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ice__thumb"} -->
<figure class="wp-block-image size-large mt-ice__thumb"><img src="<?php echo esc_url( meteora_asset( 'assets/images/ice/hoshizaki.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Hoshizaki ice', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-ice__name"} -->
<h3 class="wp-block-heading mt-ice__name"><?php echo esc_html__( 'Hoshizaki ice', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Compact cube with a clean look; balance and a constant temperature.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__type animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__type animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ice__thumb"} -->
<figure class="wp-block-image size-large mt-ice__thumb"><img src="<?php echo esc_url( meteora_asset( 'assets/images/ice/nugget.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Nugget ice', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-ice__name"} -->
<h3 class="wp-block-heading mt-ice__name"><?php echo esc_html__( 'Nugget ice', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Soft texture, pleasant to sip — for fresh, lively cocktails.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__type animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__type animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ice__thumb"} -->
<figure class="wp-block-image size-large mt-ice__thumb"><img src="<?php echo esc_url( meteora_asset( 'assets/images/ice/cube-5cm.webp' ) ); ?>" alt="<?php echo esc_attr__( '5 × 5 cm cube', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-ice__name"} -->
<h3 class="wp-block-heading mt-ice__name"><?php echo esc_html__( '5 × 5 cm cube', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Very slow melting, for Negroni, Old Fashioned and spirit-forward cocktails.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__type animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__type animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ice__thumb"} -->
<figure class="wp-block-image size-large mt-ice__thumb"><img src="<?php echo esc_url( meteora_asset( 'assets/images/ice/long-drink.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Long drink cube 4 × 4 × 12 cm', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-ice__name"} -->
<h3 class="wp-block-heading mt-ice__name"><?php echo esc_html__( 'Long drink cube 4 × 4 × 12 cm', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Vertical format for highballs and premium long drinks; slows dilution.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__type animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__type animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ice__thumb"} -->
<figure class="wp-block-image size-large mt-ice__thumb"><img src="<?php echo esc_url( meteora_asset( 'assets/images/ice/sphere.webp' ) ); ?>" alt="<?php echo esc_attr__( '50 mm sphere', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-ice__name"} -->
<h3 class="wp-block-heading mt-ice__name"><?php echo esc_html__( '50 mm sphere', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Minimal melting surface and a distinctive look in the glass.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-style-micro is-muted mt-ice__note"} -->
<p class="is-style-micro is-muted mt-ice__note"><?php echo esc_html__( 'Availability of premium formats is confirmed during the event definition phase.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></section>
<!-- /wp:group -->
