<?php
/**
 * Title: Instagram strip
 * Slug: meteora/instagram
 * Categories: meteora-sections
 * Description: Six selected images linking to Instagram (no embed).
 * Viewport Width: 1440
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:group {"tagName":"section","metadata":{"name":"Instagram"},"align":"full","className":"mt-section mt-ig","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-ig" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-ig__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ig__head"><!-- wp:group {"layout":{"type":"default"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up">Instagram</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-ig__title animate-fade-up"} -->
<h2 class="wp-block-heading mt-ig__title animate-fade-up"><?php echo wp_kses_post( __( 'Behind the bar, <em>event after event.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-button-text-link meteora-track-instagram_strip"} -->
<div class="wp-block-button is-style-button-text-link meteora-track-instagram_strip"><a class="wp-block-button__link wp-element-button" href="https://www.instagram.com/meteoraevents/">@meteoraevents</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ig__grid","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ig__grid"><!-- wp:image {"sizeSlug":"large","linkDestination":"custom","className":"mt-ig__tile hover-zoom"} -->
<figure class="wp-block-image size-large mt-ig__tile hover-zoom"><a href="https://www.instagram.com/meteoraevents/" target="_blank" rel="noreferrer noopener"><img src="<?php echo esc_url( meteora_asset( 'assets/images/towers/espresso-martini-tower.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Meteora Events on Instagram — Espresso Martini Tower', 'meteora' ); ?>"/></a></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"custom","className":"mt-ig__tile hover-zoom"} -->
<figure class="wp-block-image size-large mt-ig__tile hover-zoom"><a href="https://www.instagram.com/meteoraevents/" target="_blank" rel="noreferrer noopener"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-mirror.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Meteora Events on Instagram — Golden Mirror', 'meteora' ); ?>"/></a></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"custom","className":"mt-ig__tile hover-zoom"} -->
<figure class="wp-block-image size-large mt-ig__tile hover-zoom"><a href="https://www.instagram.com/meteoraevents/" target="_blank" rel="noreferrer noopener"><img src="<?php echo esc_url( meteora_asset( 'assets/images/details/mint-coupes.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Meteora Events on Instagram — Mint & berries', 'meteora' ); ?>"/></a></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"custom","className":"mt-ig__tile hover-zoom"} -->
<figure class="wp-block-image size-large mt-ig__tile hover-zoom"><a href="https://www.instagram.com/meteoraevents/" target="_blank" rel="noreferrer noopener"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/night-lounge.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Meteora Events on Instagram — Night bar', 'meteora' ); ?>"/></a></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"custom","className":"mt-ig__tile hover-zoom"} -->
<figure class="wp-block-image size-large mt-ig__tile hover-zoom"><a href="https://www.instagram.com/meteoraevents/" target="_blank" rel="noreferrer noopener"><img src="<?php echo esc_url( meteora_asset( 'assets/images/towers/coupe-tower-sunset.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Meteora Events on Instagram — Coupe tower', 'meteora' ); ?>"/></a></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"custom","className":"mt-ig__tile hover-zoom"} -->
<figure class="wp-block-image size-large mt-ig__tile hover-zoom"><a href="https://www.instagram.com/meteoraevents/" target="_blank" rel="noreferrer noopener"><img src="<?php echo esc_url( meteora_asset( 'assets/images/details/champagne-bowl.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Meteora Events on Instagram — Champagne bowl', 'meteora' ); ?>"/></a></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
