<?php
/**
 * Title: Page — Destination weddings
 * Slug: meteora/page-destination
 * Categories: meteora-pages
 * Description: Complete “Destination weddings” page with real content.
 * Viewport Width: 1440
 * Post Types: page
 * Block Types: core/post-content
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:cover {"url":"<?php echo esc_url( meteora_asset( 'assets/images/bars/pure-white-villa.webp' ) ); ?>","alt":"<?php echo esc_attr__( 'Pure White bar in a stone villa garden at sunset', 'meteora' ); ?>","minHeight":88,"minHeightUnit":"svh","gradient":"hero-shade","contentPosition":"bottom left","tagName":"section","align":"full","className":"mt-hero mt-hero\u002d\u002dtall animate-hero-settle","layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-cover alignfull has-custom-content-position is-position-bottom-left mt-hero mt-hero--tall animate-hero-settle" style="min-height:88svh"><img class="wp-block-cover__image-background" alt="<?php echo esc_attr__( 'Pure White bar in a stone villa garden at sunset', 'meteora' ); ?>" src="<?php echo esc_url( meteora_asset( 'assets/images/bars/pure-white-villa.webp' ) ); ?>" data-object-fit="cover"/><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim wp-block-cover__gradient-background has-background-gradient has-hero-shade-gradient-background"></span><div class="wp-block-cover__inner-container"><!-- wp:breadcrumbs {"className":"mt-crumbs"} /-->

<!-- wp:paragraph {"className":"is-style-eyebrow"} -->
<p class="is-style-eyebrow"><?php echo esc_html__( 'Based in Tuscany · Throughout Italy', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":1,"className":"mt-hero__title mt-hero__title\u002d\u002dpage"} -->
<h1 class="wp-block-heading mt-hero__title mt-hero__title--page"><?php echo wp_kses_post( __( 'Destination weddings <em>in Italy.</em>', 'meteora' ) ); ?></h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead mt-hero__lead"} -->
<p class="is-style-lead mt-hero__lead"><?php echo esc_html__( 'For couples who travel from around the world to marry in Italy, we are your Italian bar partner: cocktails, service and scenography, with the peace of mind of a local team.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"className":"mt-cta-row"} -->
<div class="wp-block-buttons mt-cta-row"><!-- wp:button {"className":"is-style-button-light meteora-track-destination_hero_quote"} -->
<div class="wp-block-button is-style-button-light meteora-track-destination_hero_quote"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>?type=destination-wedding"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></section>
<!-- /wp:cover -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Where we work"},"align":"full","className":"mt-section","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dsplit","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--split"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'Where we work', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Tuscany is home. <em>Italy is our range.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"><?php echo esc_html__( 'Our base is in Montecatini Terme. From here we reach Tuscany’s great wedding destinations, travel throughout Italy and also deliver services abroad.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest","layout":{"type":"default"}} -->
<div class="wp-block-group mt-dest"><!-- wp:group {"className":"mt-dest__row animate-fade-up has-link","layout":{"type":"default"},"anchor":"dest-tuscany"} -->
<div id="dest-tuscany" class="wp-block-group mt-dest__row animate-fade-up has-link"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><a href="<?php echo esc_url( meteora_page_url( 'tuscany' ) ); ?>"><?php echo esc_html__( 'Tuscany', 'meteora' ); ?></a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Our home base. Villas, hamlets and farmhouses where we work with the ease of locals.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-florence"} -->
<div id="dest-florence" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'Florence', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Historic palazzi, rooftop terraces and villas on the Florentine hills.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-chianti"} -->
<div id="dest-chianti" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'Chianti', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Wine estates and farmhouses among the vines, for open-air receptions.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-siena"} -->
<div id="dest-siena" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'Siena', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Medieval hamlets and country estates around Siena and the Val d’Orcia.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-lucca"} -->
<div id="dest-lucca" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'Lucca', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Lucchese villas and historic gardens, minutes from our base.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-pisa"} -->
<div id="dest-pisa" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'Pisa', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Between art city, countryside and coast.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-forte-dei-marmi"} -->
<div id="dest-forte-dei-marmi" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'Forte dei Marmi', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Seaside events on the Versilia coast, from sunset until late.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-italy"} -->
<div id="dest-italy" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'All of Italy and abroad', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'We travel throughout Italy and also deliver services outside the region and abroad.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"A local partner"},"align":"full","className":"mt-section is-style-section-alt","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section is-style-section-alt" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-ed mt-ed\u002d\u002dlandscape mt-ed\u002d\u002dpair","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ed mt-ed--landscape mt-ed--pair"><!-- wp:group {"className":"mt-ed__figure","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ed__figure"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ed__main animate-image-reveal animate-drift"} -->
<figure class="wp-block-image size-large mt-ed__main animate-image-reveal animate-drift"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-mirror.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Golden Mirror bar on a terrace overlooking the hills', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ed__second animate-image-reveal animate-delay-2"} -->
<figure class="wp-block-image size-large mt-ed__second animate-image-reveal animate-delay-2"><img src="<?php echo esc_url( meteora_asset( 'assets/images/towers/coupe-tower-sunset.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Coupe tower at sunset', 'meteora' ); ?>"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ed__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ed__text"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'A local partner', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"animate-fade-up"} -->
<h2 class="wp-block-heading animate-fade-up"><?php echo wp_kses_post( __( 'From afar, <em>in good hands.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted animate-fade-up"} -->
<p class="is-muted animate-fade-up"><?php echo esc_html__( 'Planning a wedding in another country means trusting the people on the ground. We work independently alongside your wedding planner, venue and caterer, and we reply in English and Italian.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-muted animate-fade-up"} -->
<p class="is-muted animate-fade-up"><?php echo esc_html__( 'We know Italian villas, farmhouses and historic homes: we admire them and respect them, during setup and at the end of the night.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Guide for couples"},"align":"full","className":"mt-section","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dleft","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--left"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'A guide for couples', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Your wedding bar in Italy, <em>step by step.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-num mt-num\u002d\u002d3","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num mt-num--3"><!-- wp:group {"className":"mt-num__item animate-fade-up animate-delay-1","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num__item animate-fade-up animate-delay-1"><!-- wp:paragraph {"className":"is-style-micro mt-num__n"} -->
<p class="is-style-micro mt-num__n">01</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'How bar catering works', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'We take care of the entire bar service: we design the drink list, bring the bar counter, glassware, products and ice, and run the service with our own staff. Our standard open bar lasts three hours; the Aperitivo + Open Bar package adds ninety minutes of aperitivo before dinner.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-num__item animate-fade-up animate-delay-2","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num__item animate-fade-up animate-delay-2"><!-- wp:paragraph {"className":"is-style-micro mt-num__n"} -->
<p class="is-style-micro mt-num__n">02</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'What is included', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Products and spirits from the chosen menu, a bar from the collection, our signature drink list with any customisation, professional staff, and our own glassware and setup. Extra time, additional staff and extra bar modules can be added on request.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-num__item animate-fade-up animate-delay-3","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num__item animate-fade-up animate-delay-3"><!-- wp:paragraph {"className":"is-style-micro mt-num__n"} -->
<p class="is-style-micro mt-num__n">03</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Logistics and travel', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'We are based in Montecatini Terme, in the heart of Tuscany. We work throughout Italy and abroad; any travel and logistics costs are agreed transparently in your quote.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-num__item animate-fade-up animate-delay-4","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num__item animate-fade-up animate-delay-4"><!-- wp:paragraph {"className":"is-style-micro mt-num__n"} -->
<p class="is-style-micro mt-num__n">04</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Working with your caterer', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'We are fully independent: we do not use the caterer’s kitchen, staff or equipment. Your caterer can close dinner service calmly while we carry the party forward.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-num__item animate-fade-up animate-delay-1","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num__item animate-fade-up animate-delay-1"><!-- wp:paragraph {"className":"is-style-micro mt-num__n"} -->
<p class="is-style-micro mt-num__n">05</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Choosing your bar', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Golden Mirror, Silver Reflection and Pure White, each in three sizes (1.5 m, 3.5 m, 5.5 m). We help you choose based on your venue, style and guest count.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-num__item animate-fade-up animate-delay-2","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num__item animate-fade-up animate-delay-2"><!-- wp:paragraph {"className":"is-style-micro mt-num__n"} -->
<p class="is-style-micro mt-num__n">06</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Personal touches', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Napkins and a bar front with your names (35 days’ notice), engraved fruit and ice, a cocktail list created around you. All agreed during the planning phase.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-num__item animate-fade-up animate-delay-3","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num__item animate-fade-up animate-delay-3"><!-- wp:paragraph {"className":"is-style-micro mt-num__n"} -->
<p class="is-style-micro mt-num__n">07</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'What to consider', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Guest count, length of the party, spaces for aperitivo and after-dinner, the venue’s setup times, preferred labels and alcohol-free options. The more you share, the more precise our proposal.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:buttons {"className":"mt-cta-row mt-section-cta mt-links"} -->
<div class="wp-block-buttons mt-cta-row mt-section-cta mt-links"><!-- wp:button {"className":"is-style-button-text-link"} -->
<div class="wp-block-button is-style-button-text-link"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'bars' ) ); ?>"><?php echo esc_html__( 'The bars', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link"} -->
<div class="wp-block-button is-style-button-text-link"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'cocktails' ) ); ?>">Cocktail Experience</a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link"} -->
<div class="wp-block-button is-style-button-text-link"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'services' ) ); ?>"><?php echo esc_html__( 'Services', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link"} -->
<div class="wp-block-button is-style-button-text-link"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'weddings' ) ); ?>"><?php echo esc_html__( 'Weddings', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"FAQ"},"align":"full","className":"mt-section mt-faq-section is-style-section-alt","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"62rem"}} -->
<section class="wp-block-group alignfull mt-section mt-faq-section is-style-section-alt" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dleft","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--left"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up">FAQ</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Frequently <em>asked.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:accordion {"className":"mt-faq"} -->
<div role="group" class="wp-block-accordion mt-faq"><!-- wp:accordion-item -->
<div class="wp-block-accordion-item"><!-- wp:accordion-heading -->
<h3 class="wp-block-accordion-heading has-icon has-icon-right"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title"><?php echo esc_html__( 'How does the open bar service work?', 'meteora' ); ?></span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+</span></button></h3>
<!-- /wp:accordion-heading -->

<!-- wp:accordion-panel -->
<div role="region" class="wp-block-accordion-panel"><!-- wp:paragraph -->
<p><?php echo esc_html__( 'Our team takes full responsibility for running the open bar for three hours, professionally and autonomously, in coordination with the catering. We bring the bar counter, glassware, products, ice and staff.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:accordion-panel --></div>
<!-- /wp:accordion-item -->

<!-- wp:accordion-item -->
<div class="wp-block-accordion-item"><!-- wp:accordion-heading -->
<h3 class="wp-block-accordion-heading has-icon has-icon-right"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title"><?php echo esc_html__( 'What is included?', 'meteora' ); ?></span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+</span></button></h3>
<!-- /wp:accordion-heading -->

<!-- wp:accordion-panel -->
<div role="region" class="wp-block-accordion-panel"><!-- wp:paragraph -->
<p><?php echo esc_html__( 'Products and spirits from the chosen menu, a bar counter of your choice, our signature drink list with any customisation, professional staff, fully independent service management, and our own glassware and setup. Extra time, additional staff and extra bar modules can be added on request.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:accordion-panel --></div>
<!-- /wp:accordion-item -->

<!-- wp:accordion-item -->
<div class="wp-block-accordion-item"><!-- wp:accordion-heading -->
<h3 class="wp-block-accordion-heading has-icon has-icon-right"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title"><?php echo esc_html__( 'How far do you travel?', 'meteora' ); ?></span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+</span></button></h3>
<!-- /wp:accordion-heading -->

<!-- wp:accordion-panel -->
<div role="region" class="wp-block-accordion-panel"><!-- wp:paragraph -->
<p><?php echo esc_html__( 'We are based in Montecatini Terme, Tuscany. We work throughout Italy and also deliver services outside the region and abroad. Any travel and logistics costs are agreed at the quoting stage.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:accordion-panel --></div>
<!-- /wp:accordion-item -->

<!-- wp:accordion-item -->
<div class="wp-block-accordion-item"><!-- wp:accordion-heading -->
<h3 class="wp-block-accordion-heading has-icon has-icon-right"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title"><?php echo esc_html__( 'How do you coordinate with the caterer?', 'meteora' ); ?></span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+</span></button></h3>
<!-- /wp:accordion-heading -->

<!-- wp:accordion-panel -->
<div role="region" class="wp-block-accordion-panel"><!-- wp:paragraph -->
<p><?php echo esc_html__( 'We are fully independent: we do not rely on the caterer’s kitchen, staff or equipment. This lets the caterer close dinner service calmly, load out and release their team without waiting for the after-party to end.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:accordion-panel --></div>
<!-- /wp:accordion-item -->

<!-- wp:accordion-item -->
<div class="wp-block-accordion-item"><!-- wp:accordion-heading -->
<h3 class="wp-block-accordion-heading has-icon has-icon-right"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title"><?php echo esc_html__( 'How do we choose the bar?', 'meteora' ); ?></span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+</span></button></h3>
<!-- /wp:accordion-heading -->

<!-- wp:accordion-panel -->
<div role="region" class="wp-block-accordion-panel"><!-- wp:paragraph -->
<p><?php echo esc_html__( 'Every model in the collection comes in three sizes — Slim 1.5 m, Medium 3.5 m, Large 5.5 m — chosen according to the style of the event, the venue and the guest count. We advise you during the quoting stage.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:accordion-panel --></div>
<!-- /wp:accordion-item -->

<!-- wp:accordion-item -->
<div class="wp-block-accordion-item"><!-- wp:accordion-heading -->
<h3 class="wp-block-accordion-heading has-icon has-icon-right"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title"><?php echo esc_html__( 'How early should customisations be requested?', 'meteora' ); ?></span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+</span></button></h3>
<!-- /wp:accordion-heading -->

<!-- wp:accordion-panel -->
<div role="region" class="wp-block-accordion-panel"><!-- wp:paragraph -->
<p><?php echo esc_html__( 'Custom napkins and custom bar fronts require 35 days’ notice. All customisations should be agreed during the event-planning phase.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:accordion-panel --></div>
<!-- /wp:accordion-item -->

<!-- wp:accordion-item -->
<div class="wp-block-accordion-item"><!-- wp:accordion-heading -->
<h3 class="wp-block-accordion-heading has-icon has-icon-right"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title"><?php echo esc_html__( 'Do you offer alcohol-free cocktails?', 'meteora' ); ?></span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+</span></button></h3>
<!-- /wp:accordion-heading -->

<!-- wp:accordion-panel -->
<div role="region" class="wp-block-accordion-panel"><!-- wp:paragraph -->
<p><?php echo esc_html__( 'Yes. The aperitivo drink list includes alcohol-free cocktails and fruit juices, and we can design alcohol-free options for the open bar too.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:accordion-panel --></div>
<!-- /wp:accordion-item -->

<!-- wp:accordion-item -->
<div class="wp-block-accordion-item"><!-- wp:accordion-heading -->
<h3 class="wp-block-accordion-heading has-icon has-icon-right"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title"><?php echo esc_html__( 'Can we request specific brands or glassware?', 'meteora' ); ?></span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+</span></button></h3>
<!-- /wp:accordion-heading -->

<!-- wp:accordion-panel -->
<div role="region" class="wp-block-accordion-panel"><!-- wp:paragraph -->
<p><?php echo esc_html__( 'Yes. We welcome requests for other brands, and specific glassware of any line or brand can be rented, subject to availability and supply times.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:accordion-panel --></div>
<!-- /wp:accordion-item --></div>
<!-- /wp:accordion --></section>
<!-- /wp:group -->

<!-- wp:cover {"url":"<?php echo esc_url( meteora_asset( 'assets/images/venues/fresco-hall.webp' ) ); ?>","alt":"<?php echo esc_attr__( 'Long table set in a frescoed hall', 'meteora' ); ?>","minHeight":52,"minHeightUnit":"rem","gradient":"band-shade","tagName":"section","align":"full","className":"mt-band animate-drift","layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-cover alignfull mt-band animate-drift" style="min-height:52rem"><img class="wp-block-cover__image-background" alt="<?php echo esc_attr__( 'Long table set in a frescoed hall', 'meteora' ); ?>" src="<?php echo esc_url( meteora_asset( 'assets/images/venues/fresco-hall.webp' ) ); ?>" data-object-fit="cover"/><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim wp-block-cover__gradient-background has-background-gradient has-band-shade-gradient-background"></span><div class="wp-block-cover__inner-container"><!-- wp:heading {"className":"mt-band__title animate-fade-up"} -->
<h2 class="wp-block-heading mt-band__title animate-fade-up"><?php echo wp_kses_post( __( 'Getting married in Italy? <em>Write to us.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead mt-band__lead animate-fade-up animate-delay-1"} -->
<p class="is-style-lead mt-band__lead animate-fade-up animate-delay-1"><?php echo esc_html__( 'Tell us the date, the place and the guests. We will reply with a tailored proposal.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"className":"mt-cta-row animate-fade-up animate-delay-2"} -->
<div class="wp-block-buttons mt-cta-row animate-fade-up animate-delay-2"><!-- wp:button {"className":"is-style-button-light has-arrow meteora-track-destination_band"} -->
<div class="wp-block-button is-style-button-light has-arrow meteora-track-destination_band"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>?type=destination-wedding"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></section>
<!-- /wp:cover -->
