<?php
/**
 * Title: Page — Bar: Silver Reflection
 * Slug: meteora/page-bar-silver-reflection
 * Categories: meteora-pages
 * Description: Complete “Bar: Silver Reflection” page with real content.
 * Viewport Width: 1440
 * Post Types: page
 * Block Types: core/post-content
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:group {"tagName":"section","metadata":{"name":"Silver Reflection"},"align":"full","className":"mt-section mt-bar-detail","style":{"spacing":{"padding":{"top":"var:preset|spacing|xl","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-bar-detail" style="padding-top:var(--wp--preset--spacing--xl);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-bd","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bd"><!-- wp:group {"className":"mt-bd__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bd__text"><!-- wp:breadcrumbs {"className":"mt-crumbs"} /-->

<!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'The collection', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":1,"className":"mt-bd__title"} -->
<h1 class="wp-block-heading mt-bd__title">Silver Reflection</h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bd__mood"} -->
<p class="mt-bd__mood"><?php echo esc_html__( 'Modern, brilliant, sophisticated.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-lead is-muted"} -->
<p class="is-style-lead is-muted"><?php echo esc_html__( 'Mirrored silver brings contemporary elegance and makes the most of the ambient lighting.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:group {"className":"mt-bd__facts","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bd__facts"><!-- wp:group {"layout":{"type":"default"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"is-style-micro"} -->
<p class="is-style-micro"><?php echo esc_html__( 'Ideal for', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li><?php echo esc_html__( 'Corporate events', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Chic weddings', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Minimalist design setups', 'meteora' ); ?></li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:group -->

<!-- wp:group {"layout":{"type":"default"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"is-style-micro"} -->
<p class="is-style-micro"><?php echo esc_html__( 'Sizes', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul class="wp-block-list"><!-- wp:list-item -->
<li>Slim · <?php echo esc_html__( '1.5 m', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Medium · <?php echo esc_html__( '3.5 m', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Large · <?php echo esc_html__( '5.5 m', 'meteora' ); ?></li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:buttons {"className":"mt-cta-row"} -->
<div class="wp-block-buttons mt-cta-row"><!-- wp:button {"className":"meteora-track-bar_silver-reflection_quote"} -->
<div class="wp-block-button meteora-track-bar_silver-reflection_quote"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link"} -->
<div class="wp-block-button is-style-button-text-link"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'bars' ) ); ?>"><?php echo esc_html__( 'Back to collection', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bd__media","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bd__media"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-bd__img animate-image-reveal animate-delay-1"} -->
<figure class="wp-block-image size-large mt-bd__img animate-image-reveal animate-delay-1"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/silver-reflection.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Silver Reflection bar in a large hall set for a gala dinner', 'meteora' ); ?>"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"More bars"},"align":"full","className":"mt-section is-style-section-alt","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section is-style-section-alt" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:heading {"className":"mt-bd__others-title"} -->
<h2 class="wp-block-heading mt-bd__others-title"><?php echo esc_html__( 'More from the collection', 'meteora' ); ?></h2>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-bars-grid","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bars-grid"><!-- wp:group {"className":"mt-bar","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-bar__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-bar__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-mirror-sunset.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Golden Mirror bar at sunset on a terrace overlooking the hills', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-bar__body","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__body"><!-- wp:paragraph {"className":"is-style-micro mt-bar__n"} -->
<p class="is-style-micro mt-bar__n">01</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-bar__name"} -->
<h3 class="wp-block-heading mt-bar__name"><a href="<?php echo esc_url( meteora_page_url( 'bar-golden-mirror' ) ); ?>">Golden Mirror</a></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bar__mood"} -->
<p class="mt-bar__mood"><?php echo esc_html__( 'Scenic impact, strong character.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__desc is-muted"} -->
<p class="mt-bar__desc is-muted"><?php echo esc_html__( 'Its mirrored gold surface reflects light and atmosphere, turning the bar into the focal point of the event.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__ideal"} -->
<p class="mt-bar__ideal"><?php echo wp_kses_post( __( '<span class="mt-bar__ideal-label">Ideal for</span> Glamorous receptions · Exclusive parties · Settings built for visual impact', 'meteora' ) ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-bar__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-bar__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/pure-white-villa.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Pure White bar in the garden of a stone villa at sunset', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-bar__body","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__body"><!-- wp:paragraph {"className":"is-style-micro mt-bar__n"} -->
<p class="is-style-micro mt-bar__n">03</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-bar__name"} -->
<h3 class="wp-block-heading mt-bar__name"><a href="<?php echo esc_url( meteora_page_url( 'bar-pure-white' ) ); ?>">Pure White</a></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bar__mood"} -->
<p class="mt-bar__mood"><?php echo esc_html__( 'Luminous elegance, refined texture.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__desc is-muted"} -->
<p class="mt-bar__desc is-muted"><?php echo esc_html__( 'Glossy white with a herringbone pattern creates movement and depth while keeping a clean, contemporary look.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__ideal"} -->
<p class="mt-bar__ideal"><?php echo wp_kses_post( __( '<span class="mt-bar__ideal-label">Ideal for</span> Elegant weddings · Minimalist luxury events · Sophisticated settings', 'meteora' ) ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:cover {"url":"<?php echo esc_url( meteora_asset( 'assets/images/bars/terrace-panorama.webp' ) ); ?>","alt":"<?php echo esc_attr__( 'Bar in front of a panoramic window', 'meteora' ); ?>","minHeight":52,"minHeightUnit":"rem","gradient":"band-shade","tagName":"section","align":"full","className":"mt-band animate-drift","layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-cover alignfull mt-band animate-drift" style="min-height:52rem"><img class="wp-block-cover__image-background" alt="<?php echo esc_attr__( 'Bar in front of a panoramic window', 'meteora' ); ?>" src="<?php echo esc_url( meteora_asset( 'assets/images/bars/terrace-panorama.webp' ) ); ?>" data-object-fit="cover"/><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim wp-block-cover__gradient-background has-background-gradient has-band-shade-gradient-background"></span><div class="wp-block-cover__inner-container"><!-- wp:heading {"className":"mt-band__title animate-fade-up"} -->
<h2 class="wp-block-heading mt-band__title animate-fade-up"><?php echo wp_kses_post( __( 'Picture the bar <em>at your event.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead mt-band__lead animate-fade-up animate-delay-1"} -->
<p class="is-style-lead mt-band__lead animate-fade-up animate-delay-1"><?php echo esc_html__( 'Tell us the date, the place and the guests. We will reply with a tailored proposal.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"className":"mt-cta-row animate-fade-up animate-delay-2"} -->
<div class="wp-block-buttons mt-cta-row animate-fade-up animate-delay-2"><!-- wp:button {"className":"is-style-button-light has-arrow meteora-track-bar_silver-reflection_band"} -->
<div class="wp-block-button is-style-button-light has-arrow meteora-track-bar_silver-reflection_band"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></section>
<!-- /wp:cover -->
