<?php
/**
 * Title: Page — Privacy Policy
 * Slug: meteora/page-privacy
 * Categories: meteora-pages
 * Description: Complete “Privacy Policy” page with real content.
 * Viewport Width: 1440
 * Post Types: page
 * Block Types: core/post-content
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:group {"tagName":"section","metadata":{"name":"Privacy Policy"},"align":"full","className":"mt-section mt-legal","style":{"spacing":{"padding":{"top":"var:preset|spacing|xl","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"62rem"}} -->
<section class="wp-block-group alignfull mt-section mt-legal" style="padding-top:var(--wp--preset--spacing--xl);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:breadcrumbs {"className":"mt-crumbs"} /-->

<!-- wp:heading {"level":1,"className":"mt-legal__title"} -->
<h1 class="wp-block-heading mt-legal__title"><?php echo esc_html__( 'Privacy Policy', 'meteora' ); ?></h1>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-prose","layout":{"type":"default"}} -->
<div class="wp-block-group mt-prose"><!-- wp:paragraph {"className":"is-style-micro mt-legal__draft"} -->
<p class="is-style-micro mt-legal__draft"><?php echo esc_html__( 'Draft — final legal text to be supplied by the client', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading -->
<h2 class="wp-block-heading"><?php echo esc_html__( 'Data controller', 'meteora' ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><?php echo esc_html__( '[COMPANY NAME — to be supplied], Montecatini Terme (PT), Italy. Email: info@meteoraevents.com.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading -->
<h2 class="wp-block-heading"><?php echo esc_html__( 'Data we process', 'meteora' ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><?php echo esc_html__( 'Data you provide through our contact forms (name, surname, email, phone, event details, company details where relevant) and technical browsing data.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading -->
<h2 class="wp-block-heading"><?php echo esc_html__( 'Purposes and legal basis', 'meteora' ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><?php echo esc_html__( 'Replying to information and quote requests (pre-contractual measures, Art. 6.1.b GDPR). Website usage statistics only with your consent (Art. 6.1.a GDPR).', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading -->
<h2 class="wp-block-heading"><?php echo esc_html__( 'Retention', 'meteora' ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><?php echo esc_html__( '[To be defined by the data controller.]', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading -->
<h2 class="wp-block-heading"><?php echo esc_html__( 'Recipients', 'meteora' ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><?php echo esc_html__( 'Hosting and email provider and, only if enabled with consent, analytics providers. [To be completed.]', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading -->
<h2 class="wp-block-heading"><?php echo esc_html__( 'Your rights', 'meteora' ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><?php echo esc_html__( 'Access, rectification, erasure, restriction, objection, portability, and the right to lodge a complaint with the Italian Data Protection Authority (Garante), by writing to info@meteoraevents.com.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
