<?php
/**
 * Title: Page — Services
 * Slug: meteora/page-services
 * Categories: meteora-pages
 * Description: Complete “Services” page with real content.
 * Viewport Width: 1440
 * Post Types: page
 * Block Types: core/post-content
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:group {"tagName":"section","metadata":{"name":"Page hero"},"align":"full","className":"mt-section mt-phero","style":{"spacing":{"padding":{"top":"var:preset|spacing|xl","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-phero" style="padding-top:var(--wp--preset--spacing--xl);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-phero__grid","layout":{"type":"default"}} -->
<div class="wp-block-group mt-phero__grid"><!-- wp:group {"className":"mt-phero__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-phero__text"><!-- wp:breadcrumbs {"className":"mt-crumbs"} /-->

<!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'Services', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":1,"className":"mt-phero__title animate-fade-up animate-delay-1"} -->
<h1 class="wp-block-heading mt-phero__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'From aperitivo <em>to the last drink.</em>', 'meteora' ) ); ?></h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead is-muted mt-phero__lead animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted mt-phero__lead animate-fade-up animate-delay-2"><?php echo esc_html__( 'Complete, independent formulas coordinated with your caterer — or simply our staff and our method. Every proposal is built to measure.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"className":"mt-cta-row animate-fade-up animate-delay-3"} -->
<div class="wp-block-buttons mt-cta-row animate-fade-up animate-delay-3"><!-- wp:button {"className":"is-style-button-text-link"} -->
<div class="wp-block-button is-style-button-text-link"><a class="wp-block-button__link wp-element-button" href="#essential"><?php echo esc_html__( 'Essential Experience', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link"} -->
<div class="wp-block-button is-style-button-text-link"><a class="wp-block-button__link wp-element-button" href="#premium"><?php echo esc_html__( 'Premium Experience', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link"} -->
<div class="wp-block-button is-style-button-text-link"><a class="wp-block-button__link wp-element-button" href="#aperitivo"><?php echo esc_html__( 'Aperitivo + Open Bar', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link"} -->
<div class="wp-block-button is-style-button-text-link"><a class="wp-block-button__link wp-element-button" href="#tower"><?php echo esc_html__( 'Signature Tower Experience', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link"} -->
<div class="wp-block-button is-style-button-text-link"><a class="wp-block-button__link wp-element-button" href="#bartender"><?php echo esc_html__( 'Bartender-only service', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-phero__media animate-image-reveal"} -->
<figure class="wp-block-image size-large mt-phero__media animate-image-reveal"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-marble-night.webp' ) ); ?>" alt="<?php echo esc_attr_x( 'Golden bar on a chevron floor', 'variant 2', 'meteora' ); ?>"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Service formulas"},"align":"full","className":"mt-section mt-services","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-services" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-svc","layout":{"type":"default"}} -->
<div class="wp-block-group mt-svc"><!-- wp:group {"className":"mt-svc__item","layout":{"type":"default"},"anchor":"essential"} -->
<div id="essential" class="wp-block-group mt-svc__item"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-svc__media animate-image-reveal"} -->
<figure class="wp-block-image size-large mt-svc__media animate-image-reveal"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/pure-white-villa.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Pure White bar set for an open bar at a villa', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-svc__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-svc__text"><!-- wp:paragraph {"className":"is-style-micro mt-svc__kicker"} -->
<p class="is-style-micro mt-svc__kicker">01 · <?php echo esc_html__( 'Open bar · 3 hours', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-svc__title"} -->
<h2 class="wp-block-heading mt-svc__title"><?php echo esc_html__( 'Open Bar — Essential Experience', 'meteora' ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead is-muted"} -->
<p class="is-style-lead is-muted"><?php echo esc_html__( 'Three hours of open bar run entirely by our team, independently and in step with the catering.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:list {"className":"is-style-list-ruled"} -->
<ul class="wp-block-list is-style-list-ruled"><!-- wp:list-item -->
<li><?php echo esc_html__( 'All products and spirits from the selected menu', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'A bar counter of your choice from the collection', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Our signature drink list, with any requested customisation', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Professional staff', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Fully independent service management', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Our own glassware and bar setup', 'meteora' ); ?></li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-button-outline-ink meteora-track-service_essential"} -->
<div class="wp-block-button is-style-button-outline-ink meteora-track-service_essential"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>?service=open-bar"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-svc__item mt-svc__item\u002d\u002drev","layout":{"type":"default"},"anchor":"premium"} -->
<div id="premium" class="wp-block-group mt-svc__item mt-svc__item--rev"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-svc__media animate-image-reveal"} -->
<figure class="wp-block-image size-large mt-svc__media animate-image-reveal"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-mirror-sunset.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Golden Mirror bar at sunset', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-svc__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-svc__text"><!-- wp:paragraph {"className":"is-style-micro mt-svc__kicker"} -->
<p class="is-style-micro mt-svc__kicker">02 · <?php echo esc_html__( 'Open bar · 3 hours', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-svc__title"} -->
<h2 class="wp-block-heading mt-svc__title"><?php echo esc_html__( 'Open Bar — Premium Experience', 'meteora' ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead is-muted"} -->
<p class="is-style-lead is-muted"><?php echo esc_html__( 'The same standard of service, with a premium label selection and mixers served from glass bottles.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:list {"className":"is-style-list-ruled"} -->
<ul class="wp-block-list is-style-list-ruled"><!-- wp:list-item -->
<li><?php echo esc_html__( 'Premium spirits from our seasonal selection', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Premium tonics and soft drinks in glass bottles', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'A bar counter of your choice from the collection', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Our signature drink list, with any requested customisation', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Professional staff and our own glassware', 'meteora' ); ?></li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-button-outline-ink meteora-track-service_premium"} -->
<div class="wp-block-button is-style-button-outline-ink meteora-track-service_premium"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>?service=open-bar"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-svc__item","layout":{"type":"default"},"anchor":"aperitivo"} -->
<div id="aperitivo" class="wp-block-group mt-svc__item"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-svc__media animate-image-reveal"} -->
<figure class="wp-block-image size-large mt-svc__media animate-image-reveal"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/night-lounge.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Evening bar with back bar and champagne bowl', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-svc__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-svc__text"><!-- wp:paragraph {"className":"is-style-micro mt-svc__kicker"} -->
<p class="is-style-micro mt-svc__kicker">03 · <?php echo esc_html__( '1h30 aperitivo + 3h open bar', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-svc__title"} -->
<h2 class="wp-block-heading mt-svc__title"><?php echo esc_html__( 'Aperitivo + Open Bar', 'meteora' ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead is-muted"} -->
<p class="is-style-lead is-muted"><?php echo esc_html__( 'A turnkey service, from the aperitivo to the after-dinner open bar. If both happen in the same area the aperitivo is integrated into the bar counter; otherwise it is set up on draped tables.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:list {"className":"is-style-list-ruled"} -->
<ul class="wp-block-list is-style-list-ruled"><!-- wp:list-item -->
<li><?php echo esc_html__( 'Aperol, Campari, Limoncello, Passion Fruit and Hugo Spritz', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Bellini, Mimosa, Prosecco', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Alcohol-free cocktails and fruit juices', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'One team and seamless service from aperitivo to after-dinner', 'meteora' ); ?></li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-button-outline-ink meteora-track-service_aperitivo"} -->
<div class="wp-block-button is-style-button-outline-ink meteora-track-service_aperitivo"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>?service=aperitivo-open-bar"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-svc__item mt-svc__item\u002d\u002drev","layout":{"type":"default"},"anchor":"tower"} -->
<div id="tower" class="wp-block-group mt-svc__item mt-svc__item--rev"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-svc__media animate-image-reveal"} -->
<figure class="wp-block-image size-large mt-svc__media animate-image-reveal"><img src="<?php echo esc_url( meteora_asset( 'assets/images/towers/couple-pour.webp' ) ); ?>" alt="<?php echo esc_attr_x( 'A couple pouring sparkling wine over a coupe tower', 'variant 2', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-svc__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-svc__text"><!-- wp:paragraph {"className":"is-style-micro mt-svc__kicker"} -->
<p class="is-style-micro mt-svc__kicker">04 · <?php echo esc_html__( 'A scenographic moment', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-svc__title"} -->
<h2 class="wp-block-heading mt-svc__title"><?php echo esc_html__( 'Signature Tower Experience', 'meteora' ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead is-muted"} -->
<p class="is-style-lead is-muted"><?php echo esc_html__( 'Coupes or glasses arranged in a cascade and filled live by our staff or by the couple. For toasts, cake cutting or opening the party.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:list {"className":"is-style-list-ruled"} -->
<ul class="wp-block-list is-style-list-ruled"><!-- wp:list-item -->
<li><?php echo esc_html__( 'One coupe or drink per person', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Ingredients', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Setup and equipment', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Qualified assistance staff', 'meteora' ); ?></li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-button-outline-ink meteora-track-service_tower"} -->
<div class="wp-block-button is-style-button-outline-ink meteora-track-service_tower"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>?service=signature-tower"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-svc__item","layout":{"type":"default"},"anchor":"bartender"} -->
<div id="bartender" class="wp-block-group mt-svc__item"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-svc__media animate-image-reveal"} -->
<figure class="wp-block-image size-large mt-svc__media animate-image-reveal"><img src="<?php echo esc_url( meteora_asset( 'assets/images/team/bartender-pour.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Bartender pouring a cocktail into a coupe', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-svc__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-svc__text"><!-- wp:paragraph {"className":"is-style-micro mt-svc__kicker"} -->
<p class="is-style-micro mt-svc__kicker">05 · <?php echo esc_html__( 'Meteora staff and method', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-svc__title"} -->
<h2 class="wp-block-heading mt-svc__title"><?php echo esc_html__( 'Bartender-only service', 'meteora' ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead is-muted"} -->
<p class="is-style-lead is-muted"><?php echo esc_html__( 'For clients who already have products and equipment — bar counter, glassware, ice, tools — and need qualified staff working to our method.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:list {"className":"is-style-list-ruled"} -->
<ul class="wp-block-list is-style-list-ruled"><!-- wp:list-item -->
<li><?php echo esc_html__( 'Preparation and service to professional mixology standards', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Can be combined with a waiter for order handling', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Designed for private, corporate and smaller events and receptions', 'meteora' ); ?></li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-button-outline-ink meteora-track-service_bartender"} -->
<div class="wp-block-button is-style-button-outline-ink meteora-track-service_bartender"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>?service=bartender-service"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-muted mt-svc__note"} -->
<p class="is-muted mt-svc__note"><?php echo esc_html__( 'On request: extra time, additional bartenders and waiters, extra bar modules. At peak moments, support staff keep service fast and fluid. Services can also be delivered outside the region and abroad; any logistics costs are defined in the quote.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Essential vs Premium"},"align":"full","className":"mt-section mt-compare is-style-section-alt","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-compare is-style-section-alt" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dsplit","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--split"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up">Open Bar</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Essential <em>and Premium,</em> compared.', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Essential vs Premium"},"className":"mt-cmp","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cmp"><!-- wp:table {"hasFixedLayout":false,"className":"mt-cmp__table"} -->
<figure class="wp-block-table mt-cmp__table"><table><thead><tr><th></th><th><?php echo wp_kses_post( __( '<span>Open Bar</span> Essential <em>Experience</em>', 'meteora' ) ); ?></th><th><?php echo wp_kses_post( __( '<span>Open Bar</span> Premium <em>Experience</em>', 'meteora' ) ); ?></th></tr></thead><tbody><tr><td><?php echo esc_html__( 'Spirits', 'meteora' ); ?></td><td><?php echo esc_html__( 'Reliable labels from established international houses, chosen for balance and consistency.', 'meteora' ); ?></td><td><?php echo esc_html__( 'Premium labels such as Grey Goose, Belvedere, Hendrick’s, Tanqueray No. Ten, Patrón and Diplomático.', 'meteora' ); ?></td></tr><tr><td><?php echo esc_html__( 'Mixers and soft drinks', 'meteora' ); ?></td><td><?php echo esc_html__( 'Tonics, soda and soft drinks in professional service formats.', 'meteora' ); ?></td><td><?php echo esc_html__( 'Fever-Tree tonics, soft drinks and San Pellegrino water, all in glass.', 'meteora' ); ?></td></tr><tr><td><?php echo esc_html__( 'Presentation', 'meteora' ); ?></td><td><?php echo esc_html__( 'Bar of your choice, professional glassware, fresh and dehydrated fruit, botanicals and spices.', 'meteora' ); ?></td><td><?php echo esc_html__( 'Everything in Essential, with glass bottles on display that elevate the look of the bar.', 'meteora' ); ?></td></tr><tr><td><?php echo esc_html__( 'Experience', 'meteora' ); ?></td><td><?php echo esc_html__( 'A complete, polished open bar, managed with full autonomy.', 'meteora' ); ?></td><td><?php echo esc_html__( 'For hosts who want every drink to speak the language of the great labels.', 'meteora' ); ?></td></tr></tbody></table><figcaption class="wp-element-caption"><?php echo esc_html__( 'Essential and Premium Experience compared', 'meteora' ); ?></figcaption></figure>
<!-- /wp:table -->

<!-- wp:paragraph {"className":"is-muted mt-cmp__note"} -->
<p class="is-muted mt-cmp__note"><?php echo esc_html__( 'Labels may vary with availability, replaced by equivalent or superior references and always communicated in advance. Requests for other brands are welcome.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-muted mt-cmp__note"} -->
<p class="is-muted mt-cmp__note"><?php echo esc_html__( 'Both formulas include three hours of open bar, a bar of your choice, our signature drink list, professional staff and our own glassware. Extra time, additional staff and extra bar modules on request.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"has-arrow meteora-track-comparison_quote"} -->
<div class="wp-block-button has-arrow meteora-track-comparison_quote"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Signature Tower Experience"},"align":"full","className":"mt-section mt-tw is-style-section-dark","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"},"anchor":"tower-detail"} -->
<section class="wp-block-group alignfull mt-section mt-tw is-style-section-dark" id="tower-detail" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up">Signature Tower Experience</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"is-style-display mt-tw__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading is-style-display mt-tw__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'A moment designed <em>to be remembered.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-tw__stage","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__stage"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-tw__a animate-image-reveal"} -->
<figure class="wp-block-image size-large mt-tw__a animate-image-reveal"><img src="<?php echo esc_url( meteora_asset( 'assets/images/towers/couple-pour.webp' ) ); ?>" alt="<?php echo esc_attr__( 'The couple pour sparkling wine over a coupe tower', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-tw__b animate-image-reveal animate-delay-2"} -->
<figure class="wp-block-image size-large mt-tw__b animate-image-reveal animate-delay-2"><img src="<?php echo esc_url( meteora_asset( 'assets/images/towers/coupe-tower-sunset.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Coupe tower at sunset beneath blossoming trees', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-tw__c animate-image-reveal animate-delay-3"} -->
<figure class="wp-block-image size-large mt-tw__c animate-image-reveal animate-delay-3"><img src="<?php echo esc_url( meteora_asset( 'assets/images/towers/espresso-martini-tower.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Espresso Martini Tower on a black table', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-tw__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__text"><!-- wp:paragraph {"className":"is-style-lead animate-fade-up"} -->
<p class="is-style-lead animate-fade-up"><?php echo esc_html__( 'Coupes or glasses arranged in a cascade and filled live by our staff or by the couple. For the toast, the cake cutting or opening the party: an elegant, captivating and highly photogenic moment.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:group {"className":"mt-tw__list","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__list"><!-- wp:group {"className":"mt-tw__set animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__set animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro mt-tw__group"} -->
<p class="is-style-micro mt-tw__group"><?php echo esc_html__( 'Sparkling Towers', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Classic Celebration Tower — Prosecco</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Italian Elegance Tower — Franciacorta</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Golden Cascade — Champagne</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-tw__set animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__set animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro mt-tw__group"} -->
<p class="is-style-micro mt-tw__group"><?php echo esc_html__( 'Spritz Towers', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Aperol / Campari Spritz Tower</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Hugo Spritz Tower</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-tw__set animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__set animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro mt-tw__group"} -->
<p class="is-style-micro mt-tw__group"><?php echo esc_html__( 'Espresso Martini Tower', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Espresso Martini Tower</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-muted mt-tw__small"} -->
<p class="is-muted mt-tw__small"><?php echo esc_html__( 'Would you like a different tower? Just ask. Available alongside the bar service, or on its own on request.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"FAQ"},"align":"full","className":"mt-section mt-faq-section","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"62rem"}} -->
<section class="wp-block-group alignfull mt-section mt-faq-section" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dleft","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--left"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up">FAQ</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Frequently <em>asked.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:accordion {"className":"mt-faq"} -->
<div role="group" class="wp-block-accordion mt-faq"><!-- wp:accordion-item -->
<div class="wp-block-accordion-item"><!-- wp:accordion-heading -->
<h3 class="wp-block-accordion-heading has-icon has-icon-right"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title"><?php echo esc_html__( 'How does the open bar service work?', 'meteora' ); ?></span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+</span></button></h3>
<!-- /wp:accordion-heading -->

<!-- wp:accordion-panel -->
<div role="region" class="wp-block-accordion-panel"><!-- wp:paragraph -->
<p><?php echo esc_html__( 'Our team takes full responsibility for running the open bar for three hours, professionally and autonomously, in coordination with the catering. We bring the bar counter, glassware, products, ice and staff.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:accordion-panel --></div>
<!-- /wp:accordion-item -->

<!-- wp:accordion-item -->
<div class="wp-block-accordion-item"><!-- wp:accordion-heading -->
<h3 class="wp-block-accordion-heading has-icon has-icon-right"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title"><?php echo esc_html__( 'What is included?', 'meteora' ); ?></span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+</span></button></h3>
<!-- /wp:accordion-heading -->

<!-- wp:accordion-panel -->
<div role="region" class="wp-block-accordion-panel"><!-- wp:paragraph -->
<p><?php echo esc_html__( 'Products and spirits from the chosen menu, a bar counter of your choice, our signature drink list with any customisation, professional staff, fully independent service management, and our own glassware and setup. Extra time, additional staff and extra bar modules can be added on request.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:accordion-panel --></div>
<!-- /wp:accordion-item -->

<!-- wp:accordion-item -->
<div class="wp-block-accordion-item"><!-- wp:accordion-heading -->
<h3 class="wp-block-accordion-heading has-icon has-icon-right"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title"><?php echo esc_html__( 'How far do you travel?', 'meteora' ); ?></span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+</span></button></h3>
<!-- /wp:accordion-heading -->

<!-- wp:accordion-panel -->
<div role="region" class="wp-block-accordion-panel"><!-- wp:paragraph -->
<p><?php echo esc_html__( 'We are based in Montecatini Terme, Tuscany. We work throughout Italy and also deliver services outside the region and abroad. Any travel and logistics costs are agreed at the quoting stage.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:accordion-panel --></div>
<!-- /wp:accordion-item -->

<!-- wp:accordion-item -->
<div class="wp-block-accordion-item"><!-- wp:accordion-heading -->
<h3 class="wp-block-accordion-heading has-icon has-icon-right"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title"><?php echo esc_html__( 'How do we choose the bar?', 'meteora' ); ?></span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+</span></button></h3>
<!-- /wp:accordion-heading -->

<!-- wp:accordion-panel -->
<div role="region" class="wp-block-accordion-panel"><!-- wp:paragraph -->
<p><?php echo esc_html__( 'Every model in the collection comes in three sizes — Slim 1.5 m, Medium 3.5 m, Large 5.5 m — chosen according to the style of the event, the venue and the guest count. We advise you during the quoting stage.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:accordion-panel --></div>
<!-- /wp:accordion-item -->

<!-- wp:accordion-item -->
<div class="wp-block-accordion-item"><!-- wp:accordion-heading -->
<h3 class="wp-block-accordion-heading has-icon has-icon-right"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title"><?php echo esc_html__( 'Do you offer alcohol-free cocktails?', 'meteora' ); ?></span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+</span></button></h3>
<!-- /wp:accordion-heading -->

<!-- wp:accordion-panel -->
<div role="region" class="wp-block-accordion-panel"><!-- wp:paragraph -->
<p><?php echo esc_html__( 'Yes. The aperitivo drink list includes alcohol-free cocktails and fruit juices, and we can design alcohol-free options for the open bar too.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:accordion-panel --></div>
<!-- /wp:accordion-item -->

<!-- wp:accordion-item -->
<div class="wp-block-accordion-item"><!-- wp:accordion-heading -->
<h3 class="wp-block-accordion-heading has-icon has-icon-right"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title"><?php echo esc_html__( 'Can we request specific brands or glassware?', 'meteora' ); ?></span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+</span></button></h3>
<!-- /wp:accordion-heading -->

<!-- wp:accordion-panel -->
<div role="region" class="wp-block-accordion-panel"><!-- wp:paragraph -->
<p><?php echo esc_html__( 'Yes. We welcome requests for other brands, and specific glassware of any line or brand can be rented, subject to availability and supply times.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:accordion-panel --></div>
<!-- /wp:accordion-item --></div>
<!-- /wp:accordion --></section>
<!-- /wp:group -->

<!-- wp:cover {"url":"<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-mirror.webp' ) ); ?>","alt":"<?php echo esc_attr__( 'Golden Mirror bar', 'meteora' ); ?>","minHeight":52,"minHeightUnit":"rem","gradient":"band-shade","tagName":"section","align":"full","className":"mt-band animate-drift","layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-cover alignfull mt-band animate-drift" style="min-height:52rem"><img class="wp-block-cover__image-background" alt="<?php echo esc_attr__( 'Golden Mirror bar', 'meteora' ); ?>" src="<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-mirror.webp' ) ); ?>" data-object-fit="cover"/><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim wp-block-cover__gradient-background has-background-gradient has-band-shade-gradient-background"></span><div class="wp-block-cover__inner-container"><!-- wp:heading {"className":"mt-band__title animate-fade-up"} -->
<h2 class="wp-block-heading mt-band__title animate-fade-up"><?php echo wp_kses_post( __( 'Picture the bar <em>at your event.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead mt-band__lead animate-fade-up animate-delay-1"} -->
<p class="is-style-lead mt-band__lead animate-fade-up animate-delay-1"><?php echo esc_html__( 'Tell us the date, the place and the guests. We will reply with a tailored proposal.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"className":"mt-cta-row animate-fade-up animate-delay-2"} -->
<div class="wp-block-buttons mt-cta-row animate-fade-up animate-delay-2"><!-- wp:button {"className":"is-style-button-light has-arrow meteora-track-services_band"} -->
<div class="wp-block-button is-style-button-light has-arrow meteora-track-services_band"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></section>
<!-- /wp:cover -->
