<?php
/**
 * Title: Page — Planners & venues
 * Slug: meteora/page-partners
 * Categories: meteora-pages
 * Description: Complete “Planners & venues” page with real content.
 * Viewport Width: 1440
 * Post Types: page
 * Block Types: core/post-content
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:group {"tagName":"section","metadata":{"name":"Page hero"},"align":"full","className":"mt-section mt-phero","style":{"spacing":{"padding":{"top":"var:preset|spacing|xl","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-phero" style="padding-top:var(--wp--preset--spacing--xl);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-phero__grid","layout":{"type":"default"}} -->
<div class="wp-block-group mt-phero__grid"><!-- wp:group {"className":"mt-phero__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-phero__text"><!-- wp:breadcrumbs {"className":"mt-crumbs"} /-->

<!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'For planners, venues and caterers', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":1,"className":"mt-phero__title animate-fade-up animate-delay-1"} -->
<h1 class="wp-block-heading mt-phero__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Your trusted <em>bar catering</em> partner.', 'meteora' ) ); ?></h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead is-muted mt-phero__lead animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted mt-phero__lead animate-fade-up animate-delay-2"><?php echo esc_html__( 'We work alongside wedding planners, venues, caterers and event professionals. Your event stays yours: we take care of the bar, quietly and precisely.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"className":"mt-cta-row animate-fade-up animate-delay-3"} -->
<div class="wp-block-buttons mt-cta-row animate-fade-up animate-delay-3"><!-- wp:button {"className":"meteora-track-partner_hero"} -->
<div class="wp-block-button meteora-track-partner_hero"><a class="wp-block-button__link wp-element-button" href="#partner-form"><?php echo esc_html__( 'Request partner pricing', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-phero__media animate-image-reveal"} -->
<figure class="wp-block-image size-large mt-phero__media animate-image-reveal"><img src="<?php echo esc_url( meteora_asset( 'assets/images/venues/fresco-hall.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Long table in a frescoed hall', 'meteora' ); ?>"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Who we work with"},"align":"full","className":"mt-section","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dleft","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--left"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'Who we work with', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'One goal: <em>a flawless event.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-num mt-num\u002d\u002d4","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num mt-num--4"><!-- wp:group {"className":"mt-num__item animate-fade-up animate-delay-1","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num__item animate-fade-up animate-delay-1"><!-- wp:paragraph {"className":"is-style-micro mt-num__n"} -->
<p class="is-style-micro mt-num__n">01</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Wedding planners', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'A supplier who works independently, keeps to the timeline and makes you look good in front of your clients.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-num__item animate-fade-up animate-delay-2","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num__item animate-fade-up animate-delay-2"><!-- wp:paragraph {"className":"is-style-micro mt-num__n"} -->
<p class="is-style-micro mt-num__n">02</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Venues', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Utmost care for walls, floors, furniture and gardens. We leave everything clean after service.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-num__item animate-fade-up animate-delay-3","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num__item animate-fade-up animate-delay-3"><!-- wp:paragraph {"className":"is-style-micro mt-num__n"} -->
<p class="is-style-micro mt-num__n">03</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Caterers', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Close dinner service calmly, load out and release your team: the after-party is ours.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-num__item animate-fade-up animate-delay-4","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num__item animate-fade-up animate-delay-4"><!-- wp:paragraph {"className":"is-style-micro mt-num__n"} -->
<p class="is-style-micro mt-num__n">04</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Event professionals', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'A reliable beverage partner for productions, agencies and organisers.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Benefits"},"align":"full","className":"mt-section is-style-section-dark","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section is-style-section-dark" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-split mt-split\u002d\u002dsticky","layout":{"type":"default"}} -->
<div class="wp-block-group mt-split mt-split--sticky"><!-- wp:group {"className":"mt-split__intro","layout":{"type":"default"}} -->
<div class="wp-block-group mt-split__intro"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'Why partners choose us', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"animate-fade-up"} -->
<h2 class="wp-block-heading animate-fade-up"><?php echo wp_kses_post( __( 'One less thing <em>to worry about.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ben__img animate-image-reveal"} -->
<figure class="wp-block-image size-large mt-ben__img animate-image-reveal"><img src="<?php echo esc_url( meteora_asset( 'assets/images/details/champagne-bowl.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Champagne bowl on the bar', 'meteora' ); ?>"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:list {"ordered":true,"className":"mt-ben__list"} -->
<ol class="wp-block-list mt-ben__list"><!-- wp:list-item -->
<li><?php echo esc_html__( 'Reliable, independent operation', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Professional, discreet staff', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Our own equipment and glassware', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Organised logistics', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Care for the venue', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'A visually clean service, no crates in view', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Coordination with catering', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Available throughout Italy', 'meteora' ); ?></li>
<!-- /wp:list-item --></ol>
<!-- /wp:list --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Partner form"},"align":"full","className":"mt-section is-style-section-alt","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"},"anchor":"partner-form"} -->
<section class="wp-block-group alignfull mt-section is-style-section-alt" id="partner-form" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-split mt-split\u002d\u002dsticky","layout":{"type":"default"}} -->
<div class="wp-block-group mt-split mt-split--sticky"><!-- wp:group {"className":"mt-split__intro","layout":{"type":"default"}} -->
<div class="wp-block-group mt-split__intro"><!-- wp:paragraph {"className":"is-style-eyebrow"} -->
<p class="is-style-eyebrow"><?php echo esc_html__( 'Partner area', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"anchor":"partner-form-title"} -->
<h2 id="partner-form-title" class="wp-block-heading"><?php echo wp_kses_post( __( 'Request <em>partner pricing.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Our price list for planners, venues and professionals is not public. Fill in the form and we will send you our dedicated terms and rates.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-form-wrap","layout":{"type":"default"}} -->
<div class="wp-block-group mt-form-wrap"><!-- wp:shortcode -->
[contact-form-7 title="<?php echo esc_attr__( 'Meteora — Partner pricing', 'meteora' ); ?>" html_class="mt-form mt-form--partner"]
<!-- /wp:shortcode --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"FAQ"},"align":"full","className":"mt-section mt-faq-section","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"62rem"}} -->
<section class="wp-block-group alignfull mt-section mt-faq-section" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dleft","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--left"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up">FAQ</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Frequently <em>asked.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:accordion {"className":"mt-faq"} -->
<div role="group" class="wp-block-accordion mt-faq"><!-- wp:accordion-item -->
<div class="wp-block-accordion-item"><!-- wp:accordion-heading -->
<h3 class="wp-block-accordion-heading has-icon has-icon-right"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title"><?php echo esc_html__( 'How far do you travel?', 'meteora' ); ?></span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+</span></button></h3>
<!-- /wp:accordion-heading -->

<!-- wp:accordion-panel -->
<div role="region" class="wp-block-accordion-panel"><!-- wp:paragraph -->
<p><?php echo esc_html__( 'We are based in Montecatini Terme, Tuscany. We work throughout Italy and also deliver services outside the region and abroad. Any travel and logistics costs are agreed at the quoting stage.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:accordion-panel --></div>
<!-- /wp:accordion-item -->

<!-- wp:accordion-item -->
<div class="wp-block-accordion-item"><!-- wp:accordion-heading -->
<h3 class="wp-block-accordion-heading has-icon has-icon-right"><button type="button" class="wp-block-accordion-heading__toggle"><span class="wp-block-accordion-heading__toggle-title"><?php echo esc_html__( 'How do you coordinate with the caterer?', 'meteora' ); ?></span><span class="wp-block-accordion-heading__toggle-icon" aria-hidden="true">+</span></button></h3>
<!-- /wp:accordion-heading -->

<!-- wp:accordion-panel -->
<div role="region" class="wp-block-accordion-panel"><!-- wp:paragraph -->
<p><?php echo esc_html__( 'We are fully independent: we do not rely on the caterer’s kitchen, staff or equipment. This lets the caterer close dinner service calmly, load out and release their team without waiting for the after-party to end.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:accordion-panel --></div>
<!-- /wp:accordion-item --></div>
<!-- /wp:accordion --></section>
<!-- /wp:group -->
