<?php
/**
 * Title: Page — Home
 * Slug: meteora/page-home
 * Categories: meteora-pages
 * Description: Complete “Home” page with real content.
 * Viewport Width: 1440
 * Post Types: page
 * Block Types: core/post-content
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:cover {"url":"<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-mirror-sunset.webp' ) ); ?>","alt":"<?php echo esc_attr__( 'Golden Mirror bar at sunset on a terrace overlooking the hills', 'meteora' ); ?>","focalPoint":{"x":0.5,"y":0.6},"minHeight":100,"minHeightUnit":"svh","gradient":"hero-shade","contentPosition":"bottom left","tagName":"section","align":"full","className":"mt-hero animate-hero-settle","layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-cover alignfull has-custom-content-position is-position-bottom-left mt-hero animate-hero-settle" style="min-height:100svh"><img class="wp-block-cover__image-background" alt="<?php echo esc_attr__( 'Golden Mirror bar at sunset on a terrace overlooking the hills', 'meteora' ); ?>" src="<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-mirror-sunset.webp' ) ); ?>" style="object-position:50% 60%" data-object-fit="cover" data-object-position="50% 60%"/><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim wp-block-cover__gradient-background has-background-gradient has-hero-shade-gradient-background"></span><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"className":"is-style-eyebrow"} -->
<p class="is-style-eyebrow"><?php echo esc_html__( 'Weddings · Destination weddings · Corporate · Private', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":1,"className":"mt-hero__title"} -->
<h1 class="wp-block-heading mt-hero__title"><?php echo wp_kses_post( __( 'Luxury Open Bar Catering <em>&amp; Hospitality Services</em>', 'meteora' ) ); ?></h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead mt-hero__lead"} -->
<p class="is-style-lead mt-hero__lead"><?php echo esc_html__( 'Premium bar catering for weddings, destination weddings, corporate and private events. Based in Tuscany, throughout Italy.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"className":"mt-cta-row"} -->
<div class="wp-block-buttons mt-cta-row"><!-- wp:button {"className":"is-style-button-light has-arrow meteora-track-hero_quote"} -->
<div class="wp-block-button is-style-button-light has-arrow meteora-track-hero_quote"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-ghost-light meteora-track-hero_explore"} -->
<div class="wp-block-button is-style-button-ghost-light meteora-track-hero_explore"><a class="wp-block-button__link wp-element-button" href="#experience"><?php echo esc_html__( 'Explore the experience', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></section>
<!-- /wp:cover -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Trust bar"},"align":"full","className":"mt-trust","layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-trust"><!-- wp:group {"className":"mt-trust__figure animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-trust__figure animate-fade-up"><!-- wp:paragraph {"className":"mt-trust__num"} -->
<p class="mt-trust__num"><?php echo wp_kses_post( __( '14<span>+</span>', 'meteora' ) ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"is-style-micro mt-trust__label"} -->
<h2 class="wp-block-heading is-style-micro mt-trust__label"><?php echo esc_html__( '14+ years of operational event experience', 'meteora' ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:list {"className":"mt-trust__list animate-fade-up animate-delay-2"} -->
<ul class="wp-block-list mt-trust__list animate-fade-up animate-delay-2"><!-- wp:list-item -->
<li><?php echo esc_html__( 'Professional staff', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Independent operation', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Scenographic bars', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Professional glassware', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Curated ice', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Cocktail experience', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Customisation', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Respect for venues', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Discreet hospitality', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Italy-wide service', 'meteora' ); ?></li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Not just an open bar"},"align":"full","className":"mt-section mt-experience is-style-section-dark","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"},"anchor":"experience"} -->
<section class="wp-block-group alignfull mt-section mt-experience is-style-section-dark" id="experience" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dsplit","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--split"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'Meteora Experience', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1","anchor":"experience-title"} -->
<h2 id="experience-title" class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Not just <em>an open bar.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"><?php echo esc_html__( 'We design and run the entire beverage experience of your event: from the bar to the ice, from glassware to staff, from setup to the last drink. You think about your guests.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-mosaic","layout":{"type":"default"}} -->
<div class="wp-block-group mt-mosaic"><!-- wp:group {"className":"mt-mosaic__item animate-fade-up animate-delay-1","layout":{"type":"default"}} -->
<div class="wp-block-group mt-mosaic__item animate-fade-up animate-delay-1"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-mosaic__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-mosaic__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-marble-night.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Golden bar on a chevron floor', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"is-style-micro mt-mosaic__n"} -->
<p class="is-style-micro mt-mosaic__n">01</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-mosaic__name"} -->
<h3 class="wp-block-heading mt-mosaic__name"><?php echo esc_html__( 'The bar', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-mosaic__d"} -->
<p class="mt-mosaic__d"><?php echo esc_html__( 'Scenographic, modular, in three sizes.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-mosaic__item animate-fade-up animate-delay-2","layout":{"type":"default"}} -->
<div class="wp-block-group mt-mosaic__item animate-fade-up animate-delay-2"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-mosaic__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-mosaic__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/espresso-martini.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Espresso Martini', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"is-style-micro mt-mosaic__n"} -->
<p class="is-style-micro mt-mosaic__n">02</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-mosaic__name"} -->
<h3 class="wp-block-heading mt-mosaic__name"><?php echo esc_html__( 'Cocktails', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-mosaic__d"} -->
<p class="mt-mosaic__d"><?php echo esc_html__( 'Classics made with method, bespoke signatures.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-mosaic__item animate-fade-up animate-delay-3","layout":{"type":"default"}} -->
<div class="wp-block-group mt-mosaic__item animate-fade-up animate-delay-3"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-mosaic__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-mosaic__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/team/bartender-strain.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Bartender in black uniform straining a cocktail', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"is-style-micro mt-mosaic__n"} -->
<p class="is-style-micro mt-mosaic__n">03</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-mosaic__name"} -->
<h3 class="wp-block-heading mt-mosaic__name"><?php echo esc_html__( 'Staff', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-mosaic__d"} -->
<p class="mt-mosaic__d"><?php echo esc_html__( 'Total black, discreet, professional.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-mosaic__item animate-fade-up animate-delay-1","layout":{"type":"default"}} -->
<div class="wp-block-group mt-mosaic__item animate-fade-up animate-delay-1"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-mosaic__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-mosaic__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/details/champagne-bowl.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Champagne bowl and back bar', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"is-style-micro mt-mosaic__n"} -->
<p class="is-style-micro mt-mosaic__n">04</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-mosaic__name"} -->
<h3 class="wp-block-heading mt-mosaic__name"><?php echo esc_html__( 'Glassware', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-mosaic__d"} -->
<p class="mt-mosaic__d"><?php echo esc_html__( 'The right glass for every drink.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-mosaic__item animate-fade-up animate-delay-2","layout":{"type":"default"}} -->
<div class="wp-block-group mt-mosaic__item animate-fade-up animate-delay-2"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-mosaic__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-mosaic__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/ice/cube-5cm.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Clear 5×5 cm ice cube held in a hand', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"is-style-micro mt-mosaic__n"} -->
<p class="is-style-micro mt-mosaic__n">05</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-mosaic__name"} -->
<h3 class="wp-block-heading mt-mosaic__name"><?php echo esc_html__( 'Ice', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-mosaic__d"} -->
<p class="mt-mosaic__d"><?php echo esc_html__( 'An integral part of the cocktail.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-mosaic__item animate-fade-up animate-delay-3","layout":{"type":"default"}} -->
<div class="wp-block-group mt-mosaic__item animate-fade-up animate-delay-3"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-mosaic__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-mosaic__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/details/mint-coupes.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Coupes with fresh mint and red berries', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"is-style-micro mt-mosaic__n"} -->
<p class="is-style-micro mt-mosaic__n">06</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-mosaic__name"} -->
<h3 class="wp-block-heading mt-mosaic__name"><?php echo esc_html__( 'Details', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-mosaic__d"} -->
<p class="mt-mosaic__d"><?php echo esc_html__( 'Fruit, botanicals, garnish.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-mosaic__item animate-fade-up animate-delay-1","layout":{"type":"default"}} -->
<div class="wp-block-group mt-mosaic__item animate-fade-up animate-delay-1"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-mosaic__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-mosaic__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/terrace-panorama.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Bar set up in front of a panoramic window', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"is-style-micro mt-mosaic__n"} -->
<p class="is-style-micro mt-mosaic__n">07</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-mosaic__name"} -->
<h3 class="wp-block-heading mt-mosaic__name"><?php echo esc_html__( 'Logistics', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-mosaic__d"} -->
<p class="mt-mosaic__d"><?php echo esc_html__( 'Independent from setup to load-out.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:buttons {"className":"mt-cta-row mt-section-cta"} -->
<div class="wp-block-buttons mt-cta-row mt-section-cta"><!-- wp:button {"className":"is-style-button-light"} -->
<div class="wp-block-button is-style-button-light"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'cocktails' ) ); ?>"><?php echo esc_html__( 'Discover the cocktail experience', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link meteora-track-experience_quote"} -->
<div class="wp-block-button is-style-button-text-link meteora-track-experience_quote"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Weddings"},"align":"full","className":"mt-section mt-home-weddings","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-home-weddings" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-ed mt-ed\u002d\u002dlandscape mt-ed\u002d\u002dpair","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ed mt-ed--landscape mt-ed--pair"><!-- wp:group {"className":"mt-ed__figure","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ed__figure"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ed__main animate-image-reveal animate-drift"} -->
<figure class="wp-block-image size-large mt-ed__main animate-image-reveal animate-drift"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/pure-white-villa.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Pure White bar in the garden of a stone villa', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ed__second animate-image-reveal animate-delay-2"} -->
<figure class="wp-block-image size-large mt-ed__second animate-image-reveal animate-delay-2"><img src="<?php echo esc_url( meteora_asset( 'assets/images/details/mint-coupes.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Coupes with fresh mint and red berries on the bar', 'meteora' ); ?>"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ed__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ed__text"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'Weddings', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Your wedding. <em>Your bar experience.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead is-muted animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted animate-fade-up animate-delay-2"><?php echo esc_html__( 'From the garden aperitivo to the last toast after dinner, the bar accompanies every moment of the day — and stays in the photographs.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:list {"className":"is-style-list-inline animate-fade-up animate-delay-3"} -->
<ul class="wp-block-list is-style-list-inline animate-fade-up animate-delay-3"><!-- wp:list-item -->
<li><?php echo esc_html__( 'Aperitivo', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Open bar', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Cocktails', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Signature moments', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Towers', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Customisation', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Service', 'meteora' ); ?></li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:buttons {"className":"mt-cta-row animate-fade-up animate-delay-4"} -->
<div class="wp-block-buttons mt-cta-row animate-fade-up animate-delay-4"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'weddings' ) ); ?>"><?php echo esc_html__( 'Discover wedding services', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link meteora-track-weddings_quote"} -->
<div class="wp-block-button is-style-button-text-link meteora-track-weddings_quote"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Destination weddings"},"align":"full","className":"mt-section mt-home-dest is-style-section-alt","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-home-dest is-style-section-alt" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-split mt-split\u002d\u002dsticky","layout":{"type":"default"}} -->
<div class="wp-block-group mt-split mt-split--sticky"><!-- wp:group {"className":"mt-split__intro","layout":{"type":"default"}} -->
<div class="wp-block-group mt-split__intro"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up">Destination Weddings</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Destination weddings <em>in Italy.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead is-muted animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted animate-fade-up animate-delay-2"><?php echo esc_html__( 'Based in Tuscany, available throughout Italy. For couples who choose Italy, we are the bar partner who knows the villas, the timings and the people.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'destination' ) ); ?>"><?php echo esc_html__( 'Destination weddings with Meteora', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest mt-dest\u002d\u002dcompact","layout":{"type":"default"}} -->
<div class="wp-block-group mt-dest mt-dest--compact"><!-- wp:group {"className":"mt-dest__row animate-fade-up has-link","layout":{"type":"default"},"anchor":"dest-tuscany"} -->
<div id="dest-tuscany" class="wp-block-group mt-dest__row animate-fade-up has-link"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><a href="<?php echo esc_url( meteora_page_url( 'tuscany' ) ); ?>"><?php echo esc_html__( 'Tuscany', 'meteora' ); ?></a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Our home base. Villas, hamlets and farmhouses where we work with the ease of locals.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-florence"} -->
<div id="dest-florence" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'Florence', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Historic palazzi, rooftop terraces and villas on the Florentine hills.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-chianti"} -->
<div id="dest-chianti" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'Chianti', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Wine estates and farmhouses among the vines, for open-air receptions.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-siena"} -->
<div id="dest-siena" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'Siena', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Medieval hamlets and country estates around Siena and the Val d’Orcia.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-lucca"} -->
<div id="dest-lucca" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'Lucca', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Lucchese villas and historic gardens, minutes from our base.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-pisa"} -->
<div id="dest-pisa" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'Pisa', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Between art city, countryside and coast.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-forte-dei-marmi"} -->
<div id="dest-forte-dei-marmi" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'Forte dei Marmi', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'Seaside events on the Versilia coast, from sunset until late.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-dest__row animate-fade-up","layout":{"type":"default"},"anchor":"dest-italy"} -->
<div id="dest-italy" class="wp-block-group mt-dest__row animate-fade-up"><!-- wp:paragraph {"className":"mt-dest__name"} -->
<p class="mt-dest__name"><?php echo esc_html__( 'All of Italy and abroad', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-dest__line"} -->
<p class="mt-dest__line"><?php echo esc_html__( 'We travel throughout Italy and also deliver services outside the region and abroad.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"The Bar Collection"},"align":"full","className":"mt-section mt-bars","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-bars" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dsplit","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--split"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'The Bar Collection', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'The bar <em>collection.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"><?php echo esc_html__( 'Modular, scenographic bars, each in three sizes — Slim 1.5 m, Medium 3.5 m, Large 5.5 m. A collection that keeps growing.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Bar collection"},"className":"mt-bc","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bc"><!-- wp:group {"className":"mt-bar","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-bar__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-bar__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-mirror-sunset.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Golden Mirror bar at sunset on a terrace overlooking the hills', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-bar__body","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__body"><!-- wp:paragraph {"className":"is-style-micro mt-bar__n"} -->
<p class="is-style-micro mt-bar__n"><span class="mt-bar__num">01</span></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-bar__name"} -->
<h3 class="wp-block-heading mt-bar__name"><a href="<?php echo esc_url( meteora_page_url( 'bar-golden-mirror' ) ); ?>">Golden Mirror</a></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bar__mood"} -->
<p class="mt-bar__mood"><?php echo esc_html__( 'Scenic impact, strong character.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__desc is-muted"} -->
<p class="mt-bar__desc is-muted"><?php echo esc_html__( 'Its mirrored gold surface reflects light and atmosphere, turning the bar into the focal point of the event.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__ideal"} -->
<p class="mt-bar__ideal"><?php echo wp_kses_post( __( '<span class="mt-bar__ideal-label">Ideal for</span> Glamorous receptions · Exclusive parties · Settings built for visual impact', 'meteora' ) ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-bar__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-bar__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/silver-reflection.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Silver Reflection bar in a large hall set for a gala dinner', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-bar__body","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__body"><!-- wp:paragraph {"className":"is-style-micro mt-bar__n"} -->
<p class="is-style-micro mt-bar__n"><span class="mt-bar__num">02</span></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-bar__name"} -->
<h3 class="wp-block-heading mt-bar__name"><a href="<?php echo esc_url( meteora_page_url( 'bar-silver-reflection' ) ); ?>">Silver Reflection</a></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bar__mood"} -->
<p class="mt-bar__mood"><?php echo esc_html__( 'Modern, brilliant, sophisticated.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__desc is-muted"} -->
<p class="mt-bar__desc is-muted"><?php echo esc_html__( 'Mirrored silver brings contemporary elegance and makes the most of the ambient lighting.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__ideal"} -->
<p class="mt-bar__ideal"><?php echo wp_kses_post( __( '<span class="mt-bar__ideal-label">Ideal for</span> Corporate events · Chic weddings · Minimalist design setups', 'meteora' ) ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-bar__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-bar__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/pure-white-villa.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Pure White bar in the garden of a stone villa at sunset', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-bar__body","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__body"><!-- wp:paragraph {"className":"is-style-micro mt-bar__n"} -->
<p class="is-style-micro mt-bar__n"><span class="mt-bar__num">03</span></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-bar__name"} -->
<h3 class="wp-block-heading mt-bar__name"><a href="<?php echo esc_url( meteora_page_url( 'bar-pure-white' ) ); ?>">Pure White</a></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bar__mood"} -->
<p class="mt-bar__mood"><?php echo esc_html__( 'Luminous elegance, refined texture.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__desc is-muted"} -->
<p class="mt-bar__desc is-muted"><?php echo esc_html__( 'Glossy white with a herringbone pattern creates movement and depth while keeping a clean, contemporary look.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__ideal"} -->
<p class="mt-bar__ideal"><?php echo wp_kses_post( __( '<span class="mt-bar__ideal-label">Ideal for</span> Elegant weddings · Minimalist luxury events · Sophisticated settings', 'meteora' ) ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar is-soon","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar is-soon"><!-- wp:group {"className":"mt-bar__media mt-swatch","style":{"color":{"background":"#a9b49a"}},"layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__media mt-swatch has-background" style="background-color:#a9b49a"><!-- wp:paragraph {"className":"mt-swatch__label"} -->
<p class="mt-swatch__label"><?php echo esc_html__( 'Coming soon', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar__body","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__body"><!-- wp:paragraph {"className":"is-style-micro mt-bar__n"} -->
<p class="is-style-micro mt-bar__n"><span class="mt-bar__num">04</span><span class="mt-bar__soon"><?php echo esc_html__( 'Coming soon', 'meteora' ); ?></span></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-bar__name"} -->
<h3 class="wp-block-heading mt-bar__name">Green Harmony</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bar__mood"} -->
<p class="mt-bar__mood"><?php echo esc_html__( 'Natural freshness.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__desc is-muted"} -->
<p class="mt-bar__desc is-muted"><?php echo esc_html__( 'Fresh, luminous, contemporary. The light-green finish adds an elegant botanical touch.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__ideal"} -->
<p class="mt-bar__ideal"><?php echo wp_kses_post( __( '<span class="mt-bar__ideal-label">Ideal for</span> Garden parties · Modern weddings · Eco-chic events', 'meteora' ) ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar is-soon","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar is-soon"><!-- wp:group {"className":"mt-bar__media mt-swatch","style":{"color":{"background":"#8a6a4c"}},"layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__media mt-swatch has-background" style="background-color:#8a6a4c"><!-- wp:paragraph {"className":"mt-swatch__label"} -->
<p class="mt-swatch__label"><?php echo esc_html__( 'Coming soon', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar__body","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__body"><!-- wp:paragraph {"className":"is-style-micro mt-bar__n"} -->
<p class="is-style-micro mt-bar__n"><span class="mt-bar__num">05</span><span class="mt-bar__soon"><?php echo esc_html__( 'Coming soon', 'meteora' ); ?></span></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-bar__name"} -->
<h3 class="wp-block-heading mt-bar__name">Country Classic</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bar__mood"} -->
<p class="mt-bar__mood"><?php echo esc_html__( 'Warm, natural, cosy.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__desc is-muted"} -->
<p class="mt-bar__desc is-muted"><?php echo esc_html__( 'Exposed-grain wood creates an authentic country-chic atmosphere.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__ideal"} -->
<p class="mt-bar__ideal"><?php echo wp_kses_post( __( '<span class="mt-bar__ideal-label">Ideal for</span> Outdoor events · Boho-style weddings', 'meteora' ) ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar is-soon","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar is-soon"><!-- wp:group {"className":"mt-bar__media mt-swatch","style":{"color":{"background":"#1c1614"}},"layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__media mt-swatch has-background" style="background-color:#1c1614"><!-- wp:paragraph {"className":"mt-swatch__label"} -->
<p class="mt-swatch__label"><?php echo esc_html__( 'Coming soon', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar__body","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__body"><!-- wp:paragraph {"className":"is-style-micro mt-bar__n"} -->
<p class="is-style-micro mt-bar__n"><span class="mt-bar__num">06</span><span class="mt-bar__soon"><?php echo esc_html__( 'Coming soon', 'meteora' ); ?></span></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-bar__name"} -->
<h3 class="wp-block-heading mt-bar__name">Black Essence</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bar__mood"} -->
<p class="mt-bar__mood"><?php echo esc_html__( 'Lacquered black, pure and sophisticated.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__desc is-muted"} -->
<p class="mt-bar__desc is-muted"><?php echo esc_html__( 'A bold, contemporary character that makes the bar a scenographic element of great impact.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__ideal"} -->
<p class="mt-bar__ideal"><?php echo wp_kses_post( __( '<span class="mt-bar__ideal-label">Ideal for</span> Luxury events · Gala nights · Exclusive parties · Modern minimalist weddings', 'meteora' ) ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:buttons {"className":"mt-cta-row mt-section-cta"} -->
<div class="wp-block-buttons mt-cta-row mt-section-cta"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'bars' ) ); ?>"><?php echo esc_html__( 'Explore the collection', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link meteora-track-bars_quote"} -->
<div class="wp-block-button is-style-button-text-link meteora-track-bars_quote"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Cocktail experience"},"align":"full","className":"mt-section mt-home-cocktails is-style-section-alt","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-home-cocktails is-style-section-alt" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dsplit","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--split"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up">Cocktail Experience</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Where cocktails <em>become part of the event.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"><?php echo esc_html__( 'A complete, balanced drink list, from the great classics to the Italian aperitivo, with variations on request and signatures created for you.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Cocktail families"},"className":"mt-cf","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cf"><!-- wp:group {"className":"mt-cf__frame","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cf__frame"></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cf__list","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cf__list"><!-- wp:group {"className":"mt-cf__row","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cf__row"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cf__img"} -->
<figure class="wp-block-image size-large mt-cf__img"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/old-fashioned.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Old Fashioned', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"mt-cf__name"} -->
<p class="mt-cf__name"><a href="<?php echo esc_url( meteora_page_url( 'cocktails', 'classics' ) ); ?>"><?php echo esc_html__( 'Classics', 'meteora' ); ?></a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-cf__blurb"} -->
<p class="mt-cf__blurb"><?php echo esc_html__( 'The great recipes, executed with method.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-micro mt-cf__drink"} -->
<p class="is-style-micro mt-cf__drink">Old Fashioned</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cf__row","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cf__row"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cf__img"} -->
<figure class="wp-block-image size-large mt-cf__img"><img src="<?php echo esc_url( meteora_asset( 'assets/images/details/ice-stamp.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Ice cube pressed with initials', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"mt-cf__name"} -->
<p class="mt-cf__name"><a href="<?php echo esc_url( meteora_page_url( 'cocktails', 'signature' ) ); ?>"><?php echo esc_html__( 'Signatures', 'meteora' ); ?></a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-cf__blurb"} -->
<p class="mt-cf__blurb"><?php echo esc_html__( 'Drinks created and named after your story or your brand identity.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cf__row","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cf__row"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cf__img"} -->
<figure class="wp-block-image size-large mt-cf__img"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/spritz.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Spritz', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"mt-cf__name"} -->
<p class="mt-cf__name"><a href="<?php echo esc_url( meteora_page_url( 'cocktails', 'spritz' ) ); ?>"><?php echo esc_html__( 'Spritz', 'meteora' ); ?></a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-cf__blurb"} -->
<p class="mt-cf__blurb"><?php echo esc_html__( 'Aperol, Campari, Hugo, Limoncello, Passion Fruit.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-micro mt-cf__drink"} -->
<p class="is-style-micro mt-cf__drink">Spritz</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cf__row","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cf__row"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cf__img"} -->
<figure class="wp-block-image size-large mt-cf__img"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/espresso-martini.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Espresso Martini', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"mt-cf__name"} -->
<p class="mt-cf__name"><a href="<?php echo esc_url( meteora_page_url( 'cocktails', 'martini' ) ); ?>"><?php echo esc_html__( 'Martini', 'meteora' ); ?></a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-cf__blurb"} -->
<p class="mt-cf__blurb"><?php echo esc_html__( 'Chilled coupes, clean lines.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-micro mt-cf__drink"} -->
<p class="is-style-micro mt-cf__drink">Espresso Martini</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cf__row","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cf__row"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cf__img"} -->
<figure class="wp-block-image size-large mt-cf__img"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/sour.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Whiskey · Vodka · Gin · Tequila Sour', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"mt-cf__name"} -->
<p class="mt-cf__name"><a href="<?php echo esc_url( meteora_page_url( 'cocktails', 'sour' ) ); ?>"><?php echo esc_html__( 'Sour', 'meteora' ); ?></a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-cf__blurb"} -->
<p class="mt-cf__blurb"><?php echo esc_html__( 'Balance between citrus, sweetness and structure.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-micro mt-cf__drink"} -->
<p class="is-style-micro mt-cf__drink">Whiskey · Vodka · Gin · Tequila Sour</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cf__row","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cf__row"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cf__img"} -->
<figure class="wp-block-image size-large mt-cf__img"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/mojito.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Mojito', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"mt-cf__name"} -->
<p class="mt-cf__name"><a href="<?php echo esc_url( meteora_page_url( 'cocktails', 'tropical' ) ); ?>"><?php echo esc_html__( 'Tropical', 'meteora' ); ?></a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-cf__blurb"} -->
<p class="mt-cf__blurb"><?php echo esc_html__( 'Fresh, lively, made for the party.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-micro mt-cf__drink"} -->
<p class="is-style-micro mt-cf__drink">Mojito</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cf__row","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cf__row"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cf__img"} -->
<figure class="wp-block-image size-large mt-cf__img"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/negroni.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Negroni', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"mt-cf__name"} -->
<p class="mt-cf__name"><a href="<?php echo esc_url( meteora_page_url( 'cocktails', 'aperitivo' ) ); ?>"><?php echo esc_html__( 'Italian aperitivo', 'meteora' ); ?></a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-cf__blurb"} -->
<p class="mt-cf__blurb"><?php echo esc_html__( 'The Italian ritual, from Negroni to Bellini.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-micro mt-cf__drink"} -->
<p class="is-style-micro mt-cf__drink">Negroni</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Ice"},"align":"full","className":"mt-section mt-ice is-style-section-dark","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"},"anchor":"ice"} -->
<section class="wp-block-group alignfull mt-section mt-ice is-style-section-dark" id="ice" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-ice__grid","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__grid"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ice__media animate-image-reveal animate-drift"} -->
<figure class="wp-block-image size-large mt-ice__media animate-image-reveal animate-drift"><img src="<?php echo esc_url( meteora_asset( 'assets/images/ice/pour-coupe.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Crushed ice falling into a cocktail coupe', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-ice__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__text"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'The ice we use', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"is-style-display mt-ice__title animate-fade-up animate-delay-1","anchor":"ice-title"} -->
<h2 id="ice-title" class="wp-block-heading is-style-display mt-ice__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Ice is <em>part of the cocktail.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-ice__principles","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__principles"><!-- wp:group {"className":"mt-ice__principle animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__principle animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro"} -->
<p class="is-style-micro">01</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Temperature', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Ice does not only chill: it brings the drink to the right temperature and holds it there.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__principle animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__principle animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro"} -->
<p class="is-style-micro">02</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Dilution', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Too much ice flattens a cocktail; too little makes it aggressive.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__principle animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__principle animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro"} -->
<p class="is-style-micro">03</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Texture', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'The smaller the ice, the faster it chills. The larger and denser, the more dilution is controlled over time.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__principle animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__principle animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro"} -->
<p class="is-style-micro">04</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Presentation', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'A clear cube, a sphere, a tall long-drink spear: ice is seen, and it speaks.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__principle animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__principle animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro"} -->
<p class="is-style-micro">05</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Precision', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Every cocktail has its own rules. Every cocktail begins with a precise choice.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Make it yours"},"align":"full","className":"mt-section mt-pz is-style-section-alt","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"},"anchor":"personalisation"} -->
<section class="wp-block-group alignfull mt-section mt-pz is-style-section-alt" id="personalisation" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-pz__grid","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pz__grid"><!-- wp:group {"className":"mt-pz__media","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pz__media"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-pz__img animate-image-reveal animate-drift"} -->
<figure class="wp-block-image size-large mt-pz__img animate-image-reveal animate-drift"><img src="<?php echo esc_url( meteora_asset( 'assets/images/details/ice-stamp.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Ice cube pressed with initials beside a brass stamp', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"mt-caption"} -->
<p class="mt-caption"><?php echo esc_html__( 'Initials pressed into ice. The stamp is yours to keep.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-pz__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pz__text"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html_x( 'Customisation', 'variant 2', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"animate-fade-up animate-delay-1","anchor":"personalisation-title"} -->
<h2 id="personalisation-title" class="wp-block-heading animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Make it <em>yours.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead is-muted mt-pz__lead animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted mt-pz__lead animate-fade-up animate-delay-2"><?php echo esc_html__( 'Bespoke details turn the bar service into an experience that reflects the couple, or the brand.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:group {"className":"mt-pz__list","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pz__list"><!-- wp:group {"className":"mt-pz__row animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pz__row animate-fade-up"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Custom napkins', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'With the couple’s names or a company logo.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-micro mt-pz__notice"} -->
<p class="is-style-micro mt-pz__notice"><?php echo esc_html__( '35 days’ notice', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-pz__row animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pz__row animate-fade-up"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Custom bar front', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Names or logo on the counter: the bar becomes a branded focal point.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-micro mt-pz__notice"} -->
<p class="is-style-micro mt-pz__notice"><?php echo esc_html__( '35 days’ notice', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-pz__row animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pz__row animate-fade-up"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Fruit engraving', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Names or logo etched on decorative fruit. A detail that surprises.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-pz__row animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pz__row animate-fade-up"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Ice engraving', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Logo or names pressed into large ice cubes. At the end of the event the stamp is yours to keep.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-pz__row animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pz__row animate-fade-up"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Bespoke cocktail list', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Drinks created and named after the couple’s personality or the brand identity.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-pz__row animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pz__row animate-fade-up"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Branded uniforms', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'For corporate events: logo on shirt, waistcoat and tie with screen-printed patches.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-style-micro mt-pz__foot"} -->
<p class="is-style-micro mt-pz__foot"><?php echo esc_html__( 'Customisations are agreed during the event-planning phase.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-button-text-link meteora-track-personalisation"} -->
<div class="wp-block-button is-style-button-text-link meteora-track-personalisation"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Let’s talk details', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Signature Tower Experience"},"align":"full","className":"mt-section mt-tw is-style-section-dark","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"},"anchor":"tower"} -->
<section class="wp-block-group alignfull mt-section mt-tw is-style-section-dark" id="tower" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up">Signature Tower Experience</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"is-style-display mt-tw__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading is-style-display mt-tw__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'A moment designed <em>to be remembered.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-tw__stage","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__stage"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-tw__a animate-image-reveal"} -->
<figure class="wp-block-image size-large mt-tw__a animate-image-reveal"><img src="<?php echo esc_url( meteora_asset( 'assets/images/towers/couple-pour.webp' ) ); ?>" alt="<?php echo esc_attr__( 'The couple pour sparkling wine over a coupe tower', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-tw__b animate-image-reveal animate-delay-2"} -->
<figure class="wp-block-image size-large mt-tw__b animate-image-reveal animate-delay-2"><img src="<?php echo esc_url( meteora_asset( 'assets/images/towers/coupe-tower-sunset.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Coupe tower at sunset beneath blossoming trees', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-tw__c animate-image-reveal animate-delay-3"} -->
<figure class="wp-block-image size-large mt-tw__c animate-image-reveal animate-delay-3"><img src="<?php echo esc_url( meteora_asset( 'assets/images/towers/espresso-martini-tower.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Espresso Martini Tower on a black table', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-tw__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__text"><!-- wp:paragraph {"className":"is-style-lead animate-fade-up"} -->
<p class="is-style-lead animate-fade-up"><?php echo esc_html__( 'Coupes or glasses arranged in a cascade and filled live by our staff or by the couple. For the toast, the cake cutting or opening the party: an elegant, captivating and highly photogenic moment.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:group {"className":"mt-tw__list","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__list"><!-- wp:group {"className":"mt-tw__set animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__set animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro mt-tw__group"} -->
<p class="is-style-micro mt-tw__group"><?php echo esc_html__( 'Sparkling Towers', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Classic Celebration Tower — Prosecco</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Italian Elegance Tower — Franciacorta</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Golden Cascade — Champagne</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-tw__set animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__set animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro mt-tw__group"} -->
<p class="is-style-micro mt-tw__group"><?php echo esc_html__( 'Spritz Towers', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Aperol / Campari Spritz Tower</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Hugo Spritz Tower</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-tw__set animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__set animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro mt-tw__group"} -->
<p class="is-style-micro mt-tw__group"><?php echo esc_html__( 'Espresso Martini Tower', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Espresso Martini Tower</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-muted mt-tw__small"} -->
<p class="is-muted mt-tw__small"><?php echo esc_html__( 'Would you like a different tower? Just ask. Available alongside the bar service, or on its own on request.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"className":"mt-cta-row"} -->
<div class="wp-block-buttons mt-cta-row"><!-- wp:button {"className":"is-style-button-light"} -->
<div class="wp-block-button is-style-button-light"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'services', 'tower' ) ); ?>"><?php echo esc_html__( 'Discover the Tower Experience', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link meteora-track-tower_quote"} -->
<div class="wp-block-button is-style-button-text-link meteora-track-tower_quote"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Essential vs Premium"},"align":"full","className":"mt-section mt-compare","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-compare" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dsplit","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--split"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up">Open Bar</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Two experiences, <em>one standard.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"><?php echo esc_html__( 'Essential and Premium share the same service, staff and care. What changes is the label selection, the mixers and the presentation.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Essential vs Premium"},"className":"mt-cmp","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cmp"><!-- wp:table {"hasFixedLayout":false,"className":"mt-cmp__table"} -->
<figure class="wp-block-table mt-cmp__table"><table><thead><tr><th></th><th><?php echo wp_kses_post( __( '<span>Open Bar</span> Essential <em>Experience</em>', 'meteora' ) ); ?></th><th><?php echo wp_kses_post( __( '<span>Open Bar</span> Premium <em>Experience</em>', 'meteora' ) ); ?></th></tr></thead><tbody><tr><td><?php echo esc_html__( 'Spirits', 'meteora' ); ?></td><td><?php echo esc_html__( 'Reliable labels from established international houses, chosen for balance and consistency.', 'meteora' ); ?></td><td><?php echo esc_html__( 'Premium labels such as Grey Goose, Belvedere, Hendrick’s, Tanqueray No. Ten, Patrón and Diplomático.', 'meteora' ); ?></td></tr><tr><td><?php echo esc_html__( 'Mixers and soft drinks', 'meteora' ); ?></td><td><?php echo esc_html__( 'Tonics, soda and soft drinks in professional service formats.', 'meteora' ); ?></td><td><?php echo esc_html__( 'Fever-Tree tonics, soft drinks and San Pellegrino water, all in glass.', 'meteora' ); ?></td></tr><tr><td><?php echo esc_html__( 'Presentation', 'meteora' ); ?></td><td><?php echo esc_html__( 'Bar of your choice, professional glassware, fresh and dehydrated fruit, botanicals and spices.', 'meteora' ); ?></td><td><?php echo esc_html__( 'Everything in Essential, with glass bottles on display that elevate the look of the bar.', 'meteora' ); ?></td></tr><tr><td><?php echo esc_html__( 'Experience', 'meteora' ); ?></td><td><?php echo esc_html__( 'A complete, polished open bar, managed with full autonomy.', 'meteora' ); ?></td><td><?php echo esc_html__( 'For hosts who want every drink to speak the language of the great labels.', 'meteora' ); ?></td></tr></tbody></table><figcaption class="wp-element-caption"><?php echo esc_html__( 'Essential and Premium Experience compared', 'meteora' ); ?></figcaption></figure>
<!-- /wp:table -->

<!-- wp:paragraph {"className":"is-muted mt-cmp__note"} -->
<p class="is-muted mt-cmp__note"><?php echo esc_html__( 'Labels may vary with availability, replaced by equivalent or superior references and always communicated in advance. Requests for other brands are welcome.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-muted mt-cmp__note"} -->
<p class="is-muted mt-cmp__note"><?php echo esc_html__( 'Both formulas include three hours of open bar, a bar of your choice, our signature drink list, professional staff and our own glassware. Extra time, additional staff and extra bar modules on request.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"has-arrow meteora-track-comparison_quote"} -->
<div class="wp-block-button has-arrow meteora-track-comparison_quote"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Portfolio"},"align":"full","className":"mt-section mt-portfolio is-style-section-alt","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-portfolio is-style-section-alt" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dsplit","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--split"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'Events', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Every event is <em>unique and unrepeatable.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"><?php echo esc_html__( 'What we create remains in the images, and in the memories.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:query {"queryId":7,"query":{"perPage":3,"pages":0,"offset":0,"postType":"post","order":"asc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false},"className":"mt-pg","layout":{"type":"default"}} -->
<div class="wp-block-query mt-pg"><!-- wp:post-template {"className":"mt-pg__list","layout":{"type":"default"}} -->
<!-- wp:post-featured-image {"isLink":true,"aspectRatio":"3/2","className":"mt-pg__media hover-zoom"} /-->

<!-- wp:post-terms {"term":"post_tag","separator":" — ","className":"is-style-micro mt-pg__type"} /-->

<!-- wp:post-title {"level":3,"isLink":true,"className":"mt-pg__title"} /-->

<!-- wp:post-excerpt {"showMoreOnNewLine":false,"excerptLength":30,"className":"mt-pg__excerpt"} /-->

<!-- wp:read-more {"content":"<?php echo esc_attr__( 'Read the story', 'meteora' ); ?>","className":"mt-pg__cta"} /-->
<!-- /wp:post-template --></div>
<!-- /wp:query -->

<!-- wp:buttons {"className":"mt-cta-row mt-section-cta"} -->
<div class="wp-block-buttons mt-cta-row mt-section-cta"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'events' ) ); ?>"><?php echo esc_html__( 'All events', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link meteora-track-portfolio_quote"} -->
<div class="wp-block-button is-style-button-text-link meteora-track-portfolio_quote"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Partner CTA"},"align":"full","className":"mt-section mt-pc","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-pc" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-pc__grid","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pc__grid"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-pc__media animate-image-reveal"} -->
<figure class="wp-block-image size-large mt-pc__media animate-image-reveal"><img src="<?php echo esc_url( meteora_asset( 'assets/images/venues/fresco-hall.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Long banquet table set in a frescoed hall', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-pc__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pc__text"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'Wedding planners · Venues · Caterers', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Your trusted <em>bar catering</em> partner.', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead is-muted animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted animate-fade-up animate-delay-2"><?php echo esc_html__( 'We work alongside planners, venues and caterers with our own equipment, glassware and staff. Independent, clean, discreet — anywhere in Italy.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"className":"mt-cta-row animate-fade-up animate-delay-3"} -->
<div class="wp-block-buttons mt-cta-row animate-fade-up animate-delay-3"><!-- wp:button {"className":"meteora-track-partner_band"} -->
<div class="wp-block-button meteora-track-partner_band"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'partners', 'partner-form' ) ); ?>"><?php echo esc_html__( 'Request partner pricing', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link"} -->
<div class="wp-block-button is-style-button-text-link"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'partners' ) ); ?>"><?php echo esc_html__( 'How we work with partners', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Instagram"},"align":"full","className":"mt-section mt-ig","style":{"spacing":{"padding":{"top":"0","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-ig" style="padding-top:0;padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-ig__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ig__head"><!-- wp:group {"layout":{"type":"default"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up">Instagram</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-ig__title animate-fade-up"} -->
<h2 class="wp-block-heading mt-ig__title animate-fade-up"><?php echo wp_kses_post( __( 'Behind the bar, <em>event after event.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-button-text-link meteora-track-instagram_strip"} -->
<div class="wp-block-button is-style-button-text-link meteora-track-instagram_strip"><a class="wp-block-button__link wp-element-button" href="https://www.instagram.com/meteoraevents/">@meteoraevents</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ig__grid","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ig__grid"><!-- wp:image {"sizeSlug":"large","linkDestination":"custom","className":"mt-ig__tile hover-zoom"} -->
<figure class="wp-block-image size-large mt-ig__tile hover-zoom"><a href="https://www.instagram.com/meteoraevents/" target="_blank" rel="noreferrer noopener"><img src="<?php echo esc_url( meteora_asset( 'assets/images/towers/espresso-martini-tower.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Meteora Events on Instagram — Espresso Martini Tower', 'meteora' ); ?>"/></a></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"custom","className":"mt-ig__tile hover-zoom"} -->
<figure class="wp-block-image size-large mt-ig__tile hover-zoom"><a href="https://www.instagram.com/meteoraevents/" target="_blank" rel="noreferrer noopener"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-mirror.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Meteora Events on Instagram — Golden Mirror', 'meteora' ); ?>"/></a></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"custom","className":"mt-ig__tile hover-zoom"} -->
<figure class="wp-block-image size-large mt-ig__tile hover-zoom"><a href="https://www.instagram.com/meteoraevents/" target="_blank" rel="noreferrer noopener"><img src="<?php echo esc_url( meteora_asset( 'assets/images/details/mint-coupes.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Meteora Events on Instagram — Mint & berries', 'meteora' ); ?>"/></a></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"custom","className":"mt-ig__tile hover-zoom"} -->
<figure class="wp-block-image size-large mt-ig__tile hover-zoom"><a href="https://www.instagram.com/meteoraevents/" target="_blank" rel="noreferrer noopener"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/night-lounge.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Meteora Events on Instagram — Night bar', 'meteora' ); ?>"/></a></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"custom","className":"mt-ig__tile hover-zoom"} -->
<figure class="wp-block-image size-large mt-ig__tile hover-zoom"><a href="https://www.instagram.com/meteoraevents/" target="_blank" rel="noreferrer noopener"><img src="<?php echo esc_url( meteora_asset( 'assets/images/towers/coupe-tower-sunset.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Meteora Events on Instagram — Coupe tower', 'meteora' ); ?>"/></a></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"custom","className":"mt-ig__tile hover-zoom"} -->
<figure class="wp-block-image size-large mt-ig__tile hover-zoom"><a href="https://www.instagram.com/meteoraevents/" target="_blank" rel="noreferrer noopener"><img src="<?php echo esc_url( meteora_asset( 'assets/images/details/champagne-bowl.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Meteora Events on Instagram — Champagne bowl', 'meteora' ); ?>"/></a></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:cover {"url":"<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-marble-night.webp' ) ); ?>","alt":"<?php echo esc_attr__( 'Golden bar lit up at night', 'meteora' ); ?>","minHeight":52,"minHeightUnit":"rem","gradient":"band-shade","tagName":"section","align":"full","className":"mt-band animate-drift","layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-cover alignfull mt-band animate-drift" style="min-height:52rem"><img class="wp-block-cover__image-background" alt="<?php echo esc_attr__( 'Golden bar lit up at night', 'meteora' ); ?>" src="<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-marble-night.webp' ) ); ?>" data-object-fit="cover"/><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim wp-block-cover__gradient-background has-background-gradient has-band-shade-gradient-background"></span><div class="wp-block-cover__inner-container"><!-- wp:heading {"className":"mt-band__title animate-fade-up"} -->
<h2 class="wp-block-heading mt-band__title animate-fade-up"><?php echo wp_kses_post( __( 'Picture the bar <em>at your event.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead mt-band__lead animate-fade-up animate-delay-1"} -->
<p class="is-style-lead mt-band__lead animate-fade-up animate-delay-1"><?php echo esc_html__( 'Tell us the date, the place and the guests. We will reply with a tailored proposal.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"className":"mt-cta-row animate-fade-up animate-delay-2"} -->
<div class="wp-block-buttons mt-cta-row animate-fade-up animate-delay-2"><!-- wp:button {"className":"is-style-button-light has-arrow meteora-track-home_band"} -->
<div class="wp-block-button is-style-button-light has-arrow meteora-track-home_band"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></section>
<!-- /wp:cover -->
