<?php
/**
 * Title: Page — Bars
 * Slug: meteora/page-bars
 * Categories: meteora-pages
 * Description: Complete “Bars” page with real content.
 * Viewport Width: 1440
 * Post Types: page
 * Block Types: core/post-content
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:group {"tagName":"section","metadata":{"name":"Page hero"},"align":"full","className":"mt-section mt-phero","style":{"spacing":{"padding":{"top":"var:preset|spacing|xl","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-phero" style="padding-top:var(--wp--preset--spacing--xl);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-phero__grid","layout":{"type":"default"}} -->
<div class="wp-block-group mt-phero__grid"><!-- wp:group {"className":"mt-phero__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-phero__text"><!-- wp:breadcrumbs {"className":"mt-crumbs"} /-->

<!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'The Bar Collection', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":1,"className":"mt-phero__title animate-fade-up animate-delay-1"} -->
<h1 class="wp-block-heading mt-phero__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'The bar, <em>as scenography.</em>', 'meteora' ) ); ?></h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead is-muted mt-phero__lead animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted mt-phero__lead animate-fade-up animate-delay-2"><?php echo esc_html__( 'Modular, professional, scenographic bars, chosen to match the character of your event. A collection that keeps growing.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:group {"className":"mt-sizes","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sizes"><!-- wp:group {"layout":{"type":"default"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"is-style-micro"} -->
<p class="is-style-micro">Slim</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-sizes__v"} -->
<p class="mt-sizes__v"><?php echo esc_html__( '1.5 m', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"layout":{"type":"default"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"is-style-micro"} -->
<p class="is-style-micro">Medium</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-sizes__v"} -->
<p class="mt-sizes__v"><?php echo esc_html__( '3.5 m', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"layout":{"type":"default"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"className":"is-style-micro"} -->
<p class="is-style-micro">Large</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-sizes__v"} -->
<p class="mt-sizes__v"><?php echo esc_html__( '5.5 m', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-phero__media animate-image-reveal"} -->
<figure class="wp-block-image size-large mt-phero__media animate-image-reveal"><img src="<?php echo esc_url( meteora_asset( 'assets/images/details/champagne-bowl.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Champagne bowl on a golden marble bar', 'meteora' ); ?>"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Collection"},"align":"full","className":"mt-section","style":{"spacing":{"padding":{"top":"0","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section" style="padding-top:0;padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dleft","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--left"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'Collection', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Six characters, <em>three sizes.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Bar collection"},"className":"mt-bars-grid","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bars-grid"><!-- wp:group {"className":"mt-bar animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-bar__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-bar__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-mirror-sunset.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Golden Mirror bar at sunset on a terrace overlooking the hills', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-bar__body","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__body"><!-- wp:paragraph {"className":"is-style-micro mt-bar__n"} -->
<p class="is-style-micro mt-bar__n">01</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-bar__name"} -->
<h3 class="wp-block-heading mt-bar__name"><a href="<?php echo esc_url( meteora_page_url( 'bar-golden-mirror' ) ); ?>">Golden Mirror</a></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bar__mood"} -->
<p class="mt-bar__mood"><?php echo esc_html__( 'Scenic impact, strong character.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__desc is-muted"} -->
<p class="mt-bar__desc is-muted"><?php echo esc_html__( 'Its mirrored gold surface reflects light and atmosphere, turning the bar into the focal point of the event.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__ideal"} -->
<p class="mt-bar__ideal"><?php echo wp_kses_post( __( '<span class="mt-bar__ideal-label">Ideal for</span> Glamorous receptions · Exclusive parties · Settings built for visual impact', 'meteora' ) ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-bar__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-bar__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/silver-reflection.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Silver Reflection bar in a large hall set for a gala dinner', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-bar__body","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__body"><!-- wp:paragraph {"className":"is-style-micro mt-bar__n"} -->
<p class="is-style-micro mt-bar__n">02</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-bar__name"} -->
<h3 class="wp-block-heading mt-bar__name"><a href="<?php echo esc_url( meteora_page_url( 'bar-silver-reflection' ) ); ?>">Silver Reflection</a></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bar__mood"} -->
<p class="mt-bar__mood"><?php echo esc_html__( 'Modern, brilliant, sophisticated.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__desc is-muted"} -->
<p class="mt-bar__desc is-muted"><?php echo esc_html__( 'Mirrored silver brings contemporary elegance and makes the most of the ambient lighting.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__ideal"} -->
<p class="mt-bar__ideal"><?php echo wp_kses_post( __( '<span class="mt-bar__ideal-label">Ideal for</span> Corporate events · Chic weddings · Minimalist design setups', 'meteora' ) ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-bar__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-bar__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/pure-white-villa.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Pure White bar in the garden of a stone villa at sunset', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-bar__body","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__body"><!-- wp:paragraph {"className":"is-style-micro mt-bar__n"} -->
<p class="is-style-micro mt-bar__n">03</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-bar__name"} -->
<h3 class="wp-block-heading mt-bar__name"><a href="<?php echo esc_url( meteora_page_url( 'bar-pure-white' ) ); ?>">Pure White</a></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bar__mood"} -->
<p class="mt-bar__mood"><?php echo esc_html__( 'Luminous elegance, refined texture.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__desc is-muted"} -->
<p class="mt-bar__desc is-muted"><?php echo esc_html__( 'Glossy white with a herringbone pattern creates movement and depth while keeping a clean, contemporary look.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__ideal"} -->
<p class="mt-bar__ideal"><?php echo wp_kses_post( __( '<span class="mt-bar__ideal-label">Ideal for</span> Elegant weddings · Minimalist luxury events · Sophisticated settings', 'meteora' ) ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar is-soon animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar is-soon animate-fade-up"><!-- wp:group {"className":"mt-bar__media mt-swatch","style":{"color":{"background":"#a9b49a"}},"layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__media mt-swatch has-background" style="background-color:#a9b49a"><!-- wp:paragraph {"className":"mt-swatch__label"} -->
<p class="mt-swatch__label"><?php echo esc_html__( 'Coming soon', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar__body","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__body"><!-- wp:paragraph {"className":"is-style-micro mt-bar__n"} -->
<p class="is-style-micro mt-bar__n">04 · <?php echo esc_html__( 'Coming soon', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-bar__name"} -->
<h3 class="wp-block-heading mt-bar__name">Green Harmony</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bar__mood"} -->
<p class="mt-bar__mood"><?php echo esc_html__( 'Natural freshness.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__desc is-muted"} -->
<p class="mt-bar__desc is-muted"><?php echo esc_html__( 'Fresh, luminous, contemporary. The light-green finish adds an elegant botanical touch.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__ideal"} -->
<p class="mt-bar__ideal"><?php echo wp_kses_post( __( '<span class="mt-bar__ideal-label">Ideal for</span> Garden parties · Modern weddings · Eco-chic events', 'meteora' ) ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar is-soon animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar is-soon animate-fade-up"><!-- wp:group {"className":"mt-bar__media mt-swatch","style":{"color":{"background":"#8a6a4c"}},"layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__media mt-swatch has-background" style="background-color:#8a6a4c"><!-- wp:paragraph {"className":"mt-swatch__label"} -->
<p class="mt-swatch__label"><?php echo esc_html__( 'Coming soon', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar__body","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__body"><!-- wp:paragraph {"className":"is-style-micro mt-bar__n"} -->
<p class="is-style-micro mt-bar__n">05 · <?php echo esc_html__( 'Coming soon', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-bar__name"} -->
<h3 class="wp-block-heading mt-bar__name">Country Classic</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bar__mood"} -->
<p class="mt-bar__mood"><?php echo esc_html__( 'Warm, natural, cosy.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__desc is-muted"} -->
<p class="mt-bar__desc is-muted"><?php echo esc_html__( 'Exposed-grain wood creates an authentic country-chic atmosphere.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__ideal"} -->
<p class="mt-bar__ideal"><?php echo wp_kses_post( __( '<span class="mt-bar__ideal-label">Ideal for</span> Outdoor events · Boho-style weddings', 'meteora' ) ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar is-soon animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar is-soon animate-fade-up"><!-- wp:group {"className":"mt-bar__media mt-swatch","style":{"color":{"background":"#1c1614"}},"layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__media mt-swatch has-background" style="background-color:#1c1614"><!-- wp:paragraph {"className":"mt-swatch__label"} -->
<p class="mt-swatch__label"><?php echo esc_html__( 'Coming soon', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-bar__body","layout":{"type":"default"}} -->
<div class="wp-block-group mt-bar__body"><!-- wp:paragraph {"className":"is-style-micro mt-bar__n"} -->
<p class="is-style-micro mt-bar__n">06 · <?php echo esc_html__( 'Coming soon', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3,"className":"mt-bar__name"} -->
<h3 class="wp-block-heading mt-bar__name">Black Essence</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-bar__mood"} -->
<p class="mt-bar__mood"><?php echo esc_html__( 'Lacquered black, pure and sophisticated.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__desc is-muted"} -->
<p class="mt-bar__desc is-muted"><?php echo esc_html__( 'A bold, contemporary character that makes the bar a scenographic element of great impact.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-bar__ideal"} -->
<p class="mt-bar__ideal"><?php echo wp_kses_post( __( '<span class="mt-bar__ideal-label">Ideal for</span> Luxury events · Gala nights · Exclusive parties · Modern minimalist weddings', 'meteora' ) ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-muted mt-bars__note"} -->
<p class="is-muted mt-bars__note"><?php echo esc_html__( 'Every bar comes in Slim (1.5 m), Medium (3.5 m) and Large (5.5 m), and can run in continuous extension. Extra bar modules on request.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></section>
<!-- /wp:group -->

<!-- wp:cover {"url":"<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-marble-night.webp' ) ); ?>","alt":"<?php echo esc_attr__( 'Golden bar at night', 'meteora' ); ?>","minHeight":52,"minHeightUnit":"rem","gradient":"band-shade","tagName":"section","align":"full","className":"mt-band animate-drift","layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-cover alignfull mt-band animate-drift" style="min-height:52rem"><img class="wp-block-cover__image-background" alt="<?php echo esc_attr__( 'Golden bar at night', 'meteora' ); ?>" src="<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-marble-night.webp' ) ); ?>" data-object-fit="cover"/><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim wp-block-cover__gradient-background has-background-gradient has-band-shade-gradient-background"></span><div class="wp-block-cover__inner-container"><!-- wp:heading {"className":"mt-band__title animate-fade-up"} -->
<h2 class="wp-block-heading mt-band__title animate-fade-up"><?php echo wp_kses_post( __( 'Which bar <em>for your event?</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead mt-band__lead animate-fade-up animate-delay-1"} -->
<p class="is-style-lead mt-band__lead animate-fade-up animate-delay-1"><?php echo esc_html__( 'We recommend the model and size for your venue, style and guest count.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"className":"mt-cta-row animate-fade-up animate-delay-2"} -->
<div class="wp-block-buttons mt-cta-row animate-fade-up animate-delay-2"><!-- wp:button {"className":"is-style-button-light has-arrow meteora-track-bars_band"} -->
<div class="wp-block-button is-style-button-light has-arrow meteora-track-bars_band"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></section>
<!-- /wp:cover -->
