<?php
/**
 * Title: Page — About
 * Slug: meteora/page-about
 * Categories: meteora-pages
 * Description: Complete “About” page with real content.
 * Viewport Width: 1440
 * Post Types: page
 * Block Types: core/post-content
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:group {"tagName":"section","metadata":{"name":"Page hero"},"align":"full","className":"mt-section mt-phero","style":{"spacing":{"padding":{"top":"var:preset|spacing|xl","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-phero" style="padding-top:var(--wp--preset--spacing--xl);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-phero__grid","layout":{"type":"default"}} -->
<div class="wp-block-group mt-phero__grid"><!-- wp:group {"className":"mt-phero__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-phero__text"><!-- wp:breadcrumbs {"className":"mt-crumbs"} /-->

<!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'About', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":1,"className":"mt-phero__title animate-fade-up animate-delay-1"} -->
<h1 class="wp-block-heading mt-phero__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Beverage expertise. <em>Flawless execution.</em>', 'meteora' ) ); ?></h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead is-muted mt-phero__lead animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted mt-phero__lead animate-fade-up animate-delay-2"><?php echo esc_html__( 'Meteora Events is the partner specialised in managing beverage services for high-level events. We grew out of more than 14 years of operational experience in events.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-phero__media animate-image-reveal"} -->
<figure class="wp-block-image size-large mt-phero__media animate-image-reveal"><img src="<?php echo esc_url( meteora_asset( 'assets/images/team/bartender-strain.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Bartender in a black waistcoat straining a cocktail', 'meteora' ); ?>"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Our story"},"align":"full","className":"mt-section","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-ed mt-ed\u002d\u002dlandscape mt-ed\u002d\u002dpair","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ed mt-ed--landscape mt-ed--pair"><!-- wp:group {"className":"mt-ed__figure","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ed__figure"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ed__main animate-image-reveal animate-drift"} -->
<figure class="wp-block-image size-large mt-ed__main animate-image-reveal animate-drift"><img src="<?php echo esc_url( meteora_asset( 'assets/images/bars/terrace-panorama.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Bar in front of a panoramic window', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ed__second animate-image-reveal animate-delay-2"} -->
<figure class="wp-block-image size-large mt-ed__second animate-image-reveal animate-delay-2"><img src="<?php echo esc_url( meteora_asset( 'assets/images/details/mint-coupes.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Coupes with mint and red berries', 'meteora' ); ?>"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ed__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ed__text"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'Our story', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"animate-fade-up"} -->
<h2 class="wp-block-heading animate-fade-up"><?php echo wp_kses_post( __( 'We don’t simply offer <em>a bar service.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted animate-fade-up"} -->
<p class="is-muted animate-fade-up"><?php echo esc_html__( 'We bring professionalism, method and scenographic experience, with great attention to the aesthetic and visual side of the setup. We know the dynamics of weddings, corporate and private events inside out, because we have lived them for years.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-lead animate-fade-up"} -->
<p class="is-style-lead animate-fade-up"><?php echo esc_html__( 'Every event is unique and unrepeatable, and what is created remains in the images and in the memories. That is why we aim for excellence, in service and in visual impact.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-muted animate-fade-up"} -->
<p class="is-muted animate-fade-up"><?php echo esc_html__( 'We create bar services and cocktail experiences for private clients, companies and event professionals, from our base in Montecatini Terme, Tuscany.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"How we work"},"align":"full","className":"mt-section is-style-section-alt","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section is-style-section-alt" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dleft","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--left"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'How we work', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Four words, <em>every time.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-num mt-num\u002d\u002d4 mt-values","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num mt-num--4 mt-values"><!-- wp:group {"className":"mt-num__item animate-fade-up animate-delay-1","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num__item animate-fade-up animate-delay-1"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Experience', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'More than 14 years of operational experience in events: weddings, corporate and private.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-num__item animate-fade-up animate-delay-2","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num__item animate-fade-up animate-delay-2"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Method', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Every service follows a precise method, from setup to load-out.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-num__item animate-fade-up animate-delay-3","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num__item animate-fade-up animate-delay-3"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Visual culture', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Great attention to the aesthetic and visual side of every setup.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-num__item animate-fade-up animate-delay-4","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num__item animate-fade-up animate-delay-4"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Hospitality', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Professionalism and discretion, with every guest.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Why Meteora"},"align":"full","className":"mt-section","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dsplit","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--split"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'Why Meteora', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'The details <em>that set us apart.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:buttons {"className":"mt-sh__lead"} -->
<div class="wp-block-buttons mt-sh__lead"><!-- wp:button {"className":"is-style-button-text-link"} -->
<div class="wp-block-button is-style-button-text-link"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'why' ) ); ?>"><?php echo esc_html__( 'All the reasons', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-num mt-num\u002d\u002d4 mt-why","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num mt-num--4 mt-why"><!-- wp:group {"className":"mt-num__item animate-fade-up animate-delay-1","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num__item animate-fade-up animate-delay-1"><!-- wp:paragraph {"className":"is-style-micro mt-num__n"} -->
<p class="is-style-micro mt-num__n">01</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Qualified bartenders', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Professional and reliable. Total black, no showy logos.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-num__item animate-fade-up animate-delay-2","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num__item animate-fade-up animate-delay-2"><!-- wp:paragraph {"className":"is-style-micro mt-num__n"} -->
<p class="is-style-micro mt-num__n">02</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'A clean visual service', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'No cool boxes, storage crates or glass racks in view. All restocking is done discreetly, by tray.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-num__item animate-fade-up animate-delay-3","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num__item animate-fade-up animate-delay-3"><!-- wp:paragraph {"className":"is-style-micro mt-num__n"} -->
<p class="is-style-micro mt-num__n">03</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Respect for villas and venues', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Utmost care for walls, floors, furniture and gardens during setup and after service. We leave everything clean.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-num__item animate-fade-up animate-delay-4","layout":{"type":"default"}} -->
<div class="wp-block-group mt-num__item animate-fade-up animate-delay-4"><!-- wp:paragraph {"className":"is-style-micro mt-num__n"} -->
<p class="is-style-micro mt-num__n">04</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'One less thing to worry about', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'We operate completely independently, in harmony with every other supplier.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:cover {"url":"<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-mirror-sunset.webp' ) ); ?>","alt":"<?php echo esc_attr__( 'Golden Mirror bar at sunset', 'meteora' ); ?>","minHeight":52,"minHeightUnit":"rem","gradient":"band-shade","tagName":"section","align":"full","className":"mt-band animate-drift","layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-cover alignfull mt-band animate-drift" style="min-height:52rem"><img class="wp-block-cover__image-background" alt="<?php echo esc_attr__( 'Golden Mirror bar at sunset', 'meteora' ); ?>" src="<?php echo esc_url( meteora_asset( 'assets/images/bars/golden-mirror-sunset.webp' ) ); ?>" data-object-fit="cover"/><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim wp-block-cover__gradient-background has-background-gradient has-band-shade-gradient-background"></span><div class="wp-block-cover__inner-container"><!-- wp:heading {"className":"mt-band__title animate-fade-up"} -->
<h2 class="wp-block-heading mt-band__title animate-fade-up"><?php echo wp_kses_post( __( 'Picture the bar <em>at your event.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead mt-band__lead animate-fade-up animate-delay-1"} -->
<p class="is-style-lead mt-band__lead animate-fade-up animate-delay-1"><?php echo esc_html__( 'Tell us the date, the place and the guests. We will reply with a tailored proposal.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"className":"mt-cta-row animate-fade-up animate-delay-2"} -->
<div class="wp-block-buttons mt-cta-row animate-fade-up animate-delay-2"><!-- wp:button {"className":"is-style-button-light has-arrow meteora-track-about_band"} -->
<div class="wp-block-button is-style-button-light has-arrow meteora-track-about_band"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></section>
<!-- /wp:cover -->
