<?php
/**
 * Title: Page — Cocktail Experience
 * Slug: meteora/page-cocktails
 * Categories: meteora-pages
 * Description: Complete “Cocktail Experience” page with real content.
 * Viewport Width: 1440
 * Post Types: page
 * Block Types: core/post-content
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:group {"tagName":"section","metadata":{"name":"Page hero"},"align":"full","className":"mt-section mt-phero","style":{"spacing":{"padding":{"top":"var:preset|spacing|xl","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-phero" style="padding-top:var(--wp--preset--spacing--xl);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-phero__grid","layout":{"type":"default"}} -->
<div class="wp-block-group mt-phero__grid"><!-- wp:group {"className":"mt-phero__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-phero__text"><!-- wp:breadcrumbs {"className":"mt-crumbs"} /-->

<!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up">Cocktail Experience</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":1,"className":"mt-phero__title animate-fade-up animate-delay-1"} -->
<h1 class="wp-block-heading mt-phero__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Designed to be experienced. <em>Designed to be remembered.</em>', 'meteora' ) ); ?></h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead is-muted mt-phero__lead animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted mt-phero__lead animate-fade-up animate-delay-2"><?php echo esc_html__( 'A complete, balanced selection. The way our service is built lets us prepare further classics and variations on request, depending on the ingredients available on site.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"className":"mt-cta-row animate-fade-up animate-delay-3"} -->
<div class="wp-block-buttons mt-cta-row animate-fade-up animate-delay-3"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#list"><?php echo esc_html__( 'The drink list', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link"} -->
<div class="wp-block-button is-style-button-text-link"><a class="wp-block-button__link wp-element-button" href="#ice"><?php echo esc_html__( 'The ice', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link"} -->
<div class="wp-block-button is-style-button-text-link"><a class="wp-block-button__link wp-element-button" href="#glassware"><?php echo esc_html_x( 'Glassware', 'variant 2', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-phero__media animate-image-reveal"} -->
<figure class="wp-block-image size-large mt-phero__media animate-image-reveal"><img src="<?php echo esc_url( meteora_asset( 'assets/images/team/bartender-pour.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Bartender pouring a red cocktail into a coupe', 'meteora' ); ?>"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Cocktail list"},"align":"full","className":"mt-section","style":{"spacing":{"padding":{"top":"0","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"},"anchor":"list"} -->
<section class="wp-block-group alignfull mt-section" id="list" style="padding-top:0;padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dsplit","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--split"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'Our cocktail list', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'The classics, <em>made with method.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"><?php echo esc_html__( 'Aromatic profile and alcohol level (1 to 5) for every drink. Presentation, ice and garnish may vary depending on the chosen offer.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Cocktail list"},"className":"mt-cg","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cg"><!-- wp:list {"className":"mt-cg__filters"} -->
<ul class="wp-block-list mt-cg__filters"><!-- wp:list-item -->
<li><a href="#all"><?php echo esc_html__( 'All', 'meteora' ); ?></a></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><a href="#classics"><?php echo esc_html__( 'Classics', 'meteora' ); ?></a></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><a href="#spritz"><?php echo esc_html__( 'Spritz', 'meteora' ); ?></a></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><a href="#martini"><?php echo esc_html__( 'Martini', 'meteora' ); ?></a></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><a href="#sour"><?php echo esc_html__( 'Sour', 'meteora' ); ?></a></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><a href="#tropical"><?php echo esc_html__( 'Tropical', 'meteora' ); ?></a></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><a href="#aperitivo"><?php echo esc_html__( 'Italian aperitivo', 'meteora' ); ?></a></li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:group {"className":"mt-cg__grid","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cg__grid"><!-- wp:group {"className":"mt-cc cat-spritz cat-aperitivo","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-spritz cat-aperitivo"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/spritz.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Spritz', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Spritz</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-cc__variants"} -->
<p class="mt-cc__variants">Aperol · Campari · Hugo · Limoncello</p>
<!-- /wp:paragraph -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Fresh, citrusy', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d2"} -->
<p class="mt-abv mt-abv--2"><?php echo esc_html__( 'Alcohol level: 2/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-aperitivo cat-classics","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-aperitivo cat-classics"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/negroni.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Negroni', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Negroni</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Intense, structured', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d5"} -->
<p class="mt-abv mt-abv--5"><?php echo esc_html__( 'Alcohol level: 5/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-martini","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-martini"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/espresso-martini.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Espresso Martini', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Espresso Martini</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Intense, smooth', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d4"} -->
<p class="mt-abv mt-abv--4"><?php echo esc_html__( 'Alcohol level: 4/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-martini","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-martini"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/pornstar-martini.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Pornstar Martini', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Pornstar Martini</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Fruity, sweet', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d3"} -->
<p class="mt-abv mt-abv--3"><?php echo esc_html__( 'Alcohol level: 3/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-martini cat-classics","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-martini cat-classics"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/dry-martini.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Cocktail Martini (Dry)', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Cocktail Martini (Dry)</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Dry, intense', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d5"} -->
<p class="mt-abv mt-abv--5"><?php echo esc_html__( 'Alcohol level: 5/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-sour","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-sour"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/margarita.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Margarita / Tommy’s', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Margarita / Tommy’s</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Dry, intense', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d4"} -->
<p class="mt-abv mt-abv--4"><?php echo esc_html__( 'Alcohol level: 4/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-sour","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-sour"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/sour.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Whiskey · Vodka · Gin · Tequila Sour', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Whiskey · Vodka · Gin · Tequila Sour</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Citrusy', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d4"} -->
<p class="mt-abv mt-abv--4"><?php echo esc_html__( 'Alcohol level: 4/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-sour cat-tropical","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-sour cat-tropical"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/daiquiri.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Daiquiri', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Daiquiri</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-cc__variants"} -->
<p class="mt-cc__variants">Classic · Strawberry · Passion · Mango</p>
<!-- /wp:paragraph -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Fresh, balanced', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d4"} -->
<p class="mt-abv mt-abv--4"><?php echo esc_html__( 'Alcohol level: 4/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-martini cat-sour","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-martini cat-sour"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/cosmopolitan.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Cosmopolitan', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Cosmopolitan</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Citrusy, fruity', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d3"} -->
<p class="mt-abv mt-abv--3"><?php echo esc_html__( 'Alcohol level: 3/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-sour cat-classics","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-sour cat-classics"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/gin-fizz.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Gin Fizz', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Gin Fizz</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Fresh, citrusy', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d3"} -->
<p class="mt-abv mt-abv--3"><?php echo esc_html__( 'Alcohol level: 3/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-tropical","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-tropical"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/mojito.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Mojito', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Mojito</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-cc__variants"} -->
<p class="mt-cc__variants">Classic · Passion · Fragola · Mango</p>
<!-- /wp:paragraph -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Fresh, citrusy, minty', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d2"} -->
<p class="mt-abv mt-abv--2"><?php echo esc_html__( 'Alcohol level: 2/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-tropical","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-tropical"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/caipirinha.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Caipirinha', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Caipirinha</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-cc__variants"} -->
<p class="mt-cc__variants">Caipiroska · Caipirissima · Caipirita</p>
<!-- /wp:paragraph -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Fresh, intense', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d4"} -->
<p class="mt-abv mt-abv--4"><?php echo esc_html__( 'Alcohol level: 4/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-tropical","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-tropical"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/pina-colada.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Piña Colada', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Piña Colada</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Sweet, tropical', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d3"} -->
<p class="mt-abv mt-abv--3"><?php echo esc_html__( 'Alcohol level: 3/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-tropical","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-tropical"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/paloma.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Paloma', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Paloma</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Fresh, citrusy', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d3"} -->
<p class="mt-abv mt-abv--3"><?php echo esc_html__( 'Alcohol level: 3/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-tropical cat-classics","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-tropical cat-classics"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/cuba-libre.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Cuba Libre', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Cuba Libre</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Fresh, thirst-quenching', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d3"} -->
<p class="mt-abv mt-abv--3"><?php echo esc_html__( 'Alcohol level: 3/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-aperitivo","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-aperitivo"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/americano.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Americano', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Americano</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Light, bitter', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d2"} -->
<p class="mt-abv mt-abv--2"><?php echo esc_html__( 'Alcohol level: 2/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-aperitivo","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-aperitivo"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/americano-sbagliato.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Americano Sbagliato', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Americano Sbagliato</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Light, bitter', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d2"} -->
<p class="mt-abv mt-abv--2"><?php echo esc_html__( 'Alcohol level: 2/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-aperitivo","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-aperitivo"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/garibaldi.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Garibaldi', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Garibaldi</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Soft, bitter', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d2"} -->
<p class="mt-abv mt-abv--2"><?php echo esc_html__( 'Alcohol level: 2/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-aperitivo","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-aperitivo"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/bellini.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Bellini', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Bellini</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Fruity, light', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d2"} -->
<p class="mt-abv mt-abv--2"><?php echo esc_html__( 'Alcohol level: 2/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-aperitivo","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-aperitivo"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/rossini.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Rossini', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Rossini</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Fruity, light', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d2"} -->
<p class="mt-abv mt-abv--2"><?php echo esc_html__( 'Alcohol level: 2/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-aperitivo cat-classics","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-aperitivo cat-classics"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/mimosa.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Mimosa', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Mimosa</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Citrusy, light', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d2"} -->
<p class="mt-abv mt-abv--2"><?php echo esc_html__( 'Alcohol level: 2/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-classics cat-sour","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-classics cat-sour"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/french-75.webp' ) ); ?>" alt="<?php echo esc_attr__( 'French 75', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">French 75</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Fresh, citrusy', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d3"} -->
<p class="mt-abv mt-abv--3"><?php echo esc_html__( 'Alcohol level: 3/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-classics","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-classics"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/gin-tonic.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Gin Tonic · Lemon · Soda', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Gin Tonic · Lemon · Soda</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Fresh, dry, thirst-quenching', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d3"} -->
<p class="mt-abv mt-abv--3"><?php echo esc_html__( 'Alcohol level: 3/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-classics","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-classics"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/vodka-tonic.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Vodka Tonic · Lemon · Soda', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Vodka Tonic · Lemon · Soda</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Neutral, thirst-quenching', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d3"} -->
<p class="mt-abv mt-abv--3"><?php echo esc_html__( 'Alcohol level: 3/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-classics","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-classics"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/moscow-mule.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Moscow Mule', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Moscow Mule</h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"mt-cc__variants"} -->
<p class="mt-cc__variants">London · Jalisco · Kentucky</p>
<!-- /wp:paragraph -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Fresh, spiced', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d3"} -->
<p class="mt-abv mt-abv--3"><?php echo esc_html__( 'Alcohol level: 3/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-classics","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-classics"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/old-fashioned.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Old Fashioned', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Old Fashioned</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Intense, structured', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d5"} -->
<p class="mt-abv mt-abv--5"><?php echo esc_html__( 'Alcohol level: 5/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-classics","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-classics"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/manhattan.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Manhattan', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Manhattan</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Intense, dry', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d5"} -->
<p class="mt-abv mt-abv--5"><?php echo esc_html__( 'Alcohol level: 5/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-classics","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-classics"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/long-island.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Long Island Iced Tea', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Long Island Iced Tea</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Fresh, sweet', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d5"} -->
<p class="mt-abv mt-abv--5"><?php echo esc_html__( 'Alcohol level: 5/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-classics","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-classics"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/black-russian.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Black Russian', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Black Russian</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Intense, smooth', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d4"} -->
<p class="mt-abv mt-abv--4"><?php echo esc_html__( 'Alcohol level: 4/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-cc cat-classics","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc cat-classics"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-cc__media hover-zoom"} -->
<figure class="wp-block-image size-large mt-cc__media hover-zoom"><img src="<?php echo esc_url( meteora_asset( 'assets/images/cocktails/screwdriver.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Screwdriver', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-cc__name"} -->
<h3 class="wp-block-heading mt-cc__name">Screwdriver</h3>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-cc__meta","layout":{"type":"default"}} -->
<div class="wp-block-group mt-cc__meta"><!-- wp:paragraph {"className":"mt-cc__profile"} -->
<p class="mt-cc__profile"><?php echo esc_html__( 'Fresh, citrusy', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-abv mt-abv\u002d\u002d3"} -->
<p class="mt-abv mt-abv--3"><?php echo esc_html__( 'Alcohol level: 3/5', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Signature"},"align":"full","className":"mt-section is-style-section-alt","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"},"anchor":"signature"} -->
<section class="wp-block-group alignfull mt-section is-style-section-alt" id="signature" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-ed mt-ed\u002d\u002dportrait mt-ed\u002d\u002dpair","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ed mt-ed--portrait mt-ed--pair"><!-- wp:group {"className":"mt-ed__figure","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ed__figure"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ed__main animate-image-reveal animate-drift"} -->
<figure class="wp-block-image size-large mt-ed__main animate-image-reveal animate-drift"><img src="<?php echo esc_url( meteora_asset( 'assets/images/details/ice-stamp.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Ice cube pressed with initials', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ed__second animate-image-reveal animate-delay-2"} -->
<figure class="wp-block-image size-large mt-ed__second animate-image-reveal animate-delay-2"><img src="<?php echo esc_url( meteora_asset( 'assets/images/team/bartender-strain.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Bartender straining a cocktail', 'meteora' ); ?>"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ed__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ed__text"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'Signatures', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"animate-fade-up"} -->
<h2 class="wp-block-heading animate-fade-up"><?php echo wp_kses_post( __( 'A cocktail <em>with your name on it.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead is-muted animate-fade-up"} -->
<p class="is-style-lead is-muted animate-fade-up"><?php echo esc_html__( 'Drinks created and named after your story or your brand identity.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-muted animate-fade-up"} -->
<p class="is-muted animate-fade-up"><?php echo esc_html__( 'A bespoke cocktail list takes shape during event planning: we start from your story, the flavours you love or your brand colours, and turn them into drinks.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-button-text-link meteora-track-signature_quote"} -->
<div class="wp-block-button is-style-button-text-link meteora-track-signature_quote"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Ice"},"align":"full","className":"mt-section mt-ice is-style-section-dark","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"},"anchor":"ice"} -->
<section class="wp-block-group alignfull mt-section mt-ice is-style-section-dark" id="ice" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-ice__grid","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__grid"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ice__media animate-image-reveal animate-drift"} -->
<figure class="wp-block-image size-large mt-ice__media animate-image-reveal animate-drift"><img src="<?php echo esc_url( meteora_asset( 'assets/images/ice/pour-coupe.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Crushed ice falling into a cocktail coupe', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-ice__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__text"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'The ice we use', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"is-style-display mt-ice__title animate-fade-up animate-delay-1","anchor":"ice-title"} -->
<h2 id="ice-title" class="wp-block-heading is-style-display mt-ice__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Ice is <em>part of the cocktail.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-ice__principles","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__principles"><!-- wp:group {"className":"mt-ice__principle animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__principle animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro"} -->
<p class="is-style-micro">01</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Temperature', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Ice does not only chill: it brings the drink to the right temperature and holds it there.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__principle animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__principle animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro"} -->
<p class="is-style-micro">02</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Dilution', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Too much ice flattens a cocktail; too little makes it aggressive.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__principle animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__principle animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro"} -->
<p class="is-style-micro">03</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Texture', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'The smaller the ice, the faster it chills. The larger and denser, the more dilution is controlled over time.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__principle animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__principle animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro"} -->
<p class="is-style-micro">04</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Presentation', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'A clear cube, a sphere, a tall long-drink spear: ice is seen, and it speaks.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__principle animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__principle animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro"} -->
<p class="is-style-micro">05</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Precision', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Every cocktail has its own rules. Every cocktail begins with a precise choice.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__rail","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__rail"><!-- wp:group {"className":"mt-ice__type animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__type animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ice__thumb"} -->
<figure class="wp-block-image size-large mt-ice__thumb"><img src="<?php echo esc_url( meteora_asset( 'assets/images/ice/compact-cube.webp' ) ); ?>" alt="<?php echo esc_attr__( 'High-density compact cube', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-ice__name"} -->
<h3 class="wp-block-heading mt-ice__name"><?php echo esc_html__( 'High-density compact cube', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Slow melting, controlled dilution in long drinks and structured cocktails.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__type animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__type animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ice__thumb"} -->
<figure class="wp-block-image size-large mt-ice__thumb"><img src="<?php echo esc_url( meteora_asset( 'assets/images/ice/hoshizaki.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Hoshizaki ice', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-ice__name"} -->
<h3 class="wp-block-heading mt-ice__name"><?php echo esc_html__( 'Hoshizaki ice', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Compact cube with a clean look; balance and a constant temperature.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__type animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__type animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ice__thumb"} -->
<figure class="wp-block-image size-large mt-ice__thumb"><img src="<?php echo esc_url( meteora_asset( 'assets/images/ice/nugget.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Nugget ice', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-ice__name"} -->
<h3 class="wp-block-heading mt-ice__name"><?php echo esc_html__( 'Nugget ice', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Soft texture, pleasant to sip — for fresh, lively cocktails.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__type animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__type animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ice__thumb"} -->
<figure class="wp-block-image size-large mt-ice__thumb"><img src="<?php echo esc_url( meteora_asset( 'assets/images/ice/cube-5cm.webp' ) ); ?>" alt="<?php echo esc_attr__( '5 × 5 cm cube', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-ice__name"} -->
<h3 class="wp-block-heading mt-ice__name"><?php echo esc_html__( '5 × 5 cm cube', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Very slow melting, for Negroni, Old Fashioned and spirit-forward cocktails.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__type animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__type animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ice__thumb"} -->
<figure class="wp-block-image size-large mt-ice__thumb"><img src="<?php echo esc_url( meteora_asset( 'assets/images/ice/long-drink.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Long drink cube 4 × 4 × 12 cm', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-ice__name"} -->
<h3 class="wp-block-heading mt-ice__name"><?php echo esc_html__( 'Long drink cube 4 × 4 × 12 cm', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Vertical format for highballs and premium long drinks; slows dilution.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-ice__type animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-ice__type animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-ice__thumb"} -->
<figure class="wp-block-image size-large mt-ice__thumb"><img src="<?php echo esc_url( meteora_asset( 'assets/images/ice/sphere.webp' ) ); ?>" alt="<?php echo esc_attr__( '50 mm sphere', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3,"className":"mt-ice__name"} -->
<h3 class="wp-block-heading mt-ice__name"><?php echo esc_html__( '50 mm sphere', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Minimal melting surface and a distinctive look in the glass.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-style-micro is-muted mt-ice__note"} -->
<p class="is-style-micro is-muted mt-ice__note"><?php echo esc_html__( 'Availability of premium formats is confirmed during the event definition phase.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Glassware"},"align":"full","className":"mt-section mt-gl","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"},"anchor":"glassware"} -->
<section class="wp-block-group alignfull mt-section mt-gl" id="glassware" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-gl__top","layout":{"type":"default"}} -->
<div class="wp-block-group mt-gl__top"><!-- wp:group {"className":"mt-sh mt-sh\u002d\u002dleft","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh mt-sh--left"><!-- wp:group {"className":"mt-sh__head","layout":{"type":"default"}} -->
<div class="wp-block-group mt-sh__head"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html__( 'Our glassware', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"mt-sh__title animate-fade-up animate-delay-1","anchor":"glass-title"} -->
<h2 id="glass-title" class="wp-block-heading mt-sh__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'The right glass <em>for the right cocktail.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted mt-sh__lead animate-fade-up animate-delay-2"><?php echo esc_html__( 'Shape, thickness, opening and capacity are chosen for each cocktail: to manage temperature and dilution and to showcase its aromas. Professional HoReCa-grade glass, with lines that match the style of the setup.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-gl__hero animate-image-reveal"} -->
<figure class="wp-block-image size-large mt-gl__hero animate-image-reveal"><img src="<?php echo esc_url( meteora_asset( 'assets/images/glassware/crystal.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Cut-crystal tumblers lined up on the bar', 'meteora' ); ?>"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-gl__grid","layout":{"type":"default"}} -->
<div class="wp-block-group mt-gl__grid"><!-- wp:group {"className":"mt-gl__item animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-gl__item animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-gl__tile"} -->
<figure class="wp-block-image size-large mt-gl__tile"><img src="<?php echo esc_url( meteora_asset( 'assets/images/glassware/wine.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Wine glass', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Wine glass', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Spritz, sparkling, wine', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-gl__item animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-gl__item animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-gl__tile"} -->
<figure class="wp-block-image size-large mt-gl__tile"><img src="<?php echo esc_url( meteora_asset( 'assets/images/glassware/martini.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Martini coupe', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Martini coupe', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Martinis, sours, drinks served up', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-gl__item animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-gl__item animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-gl__tile"} -->
<figure class="wp-block-image size-large mt-gl__tile"><img src="<?php echo esc_url( meteora_asset( 'assets/images/glassware/old-fashioned.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Old Fashioned', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Old Fashioned', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Spirit-forward drinks over large ice', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-gl__item animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-gl__item animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-gl__tile"} -->
<figure class="wp-block-image size-large mt-gl__tile"><img src="<?php echo esc_url( meteora_asset( 'assets/images/glassware/long-drink.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Long drink', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Long drink', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Highballs, tonics, Mojito', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-gl__item animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-gl__item animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-gl__tile"} -->
<figure class="wp-block-image size-large mt-gl__tile"><img src="<?php echo esc_url( meteora_asset( 'assets/images/glassware/highball.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Highball tumbler', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Highball tumbler', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Short, refreshing serves', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-gl__item animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-gl__item animate-fade-up"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-gl__tile"} -->
<figure class="wp-block-image size-large mt-gl__tile"><img src="<?php echo esc_url( meteora_asset( 'assets/images/glassware/shot.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Shot glass', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Shot glass', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Shots and tastings', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-muted mt-gl__note"} -->
<p class="is-muted mt-gl__note"><?php echo esc_html__( 'On request, specific glassware of any line or brand can be rented, subject to availability and supply times.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></section>
<!-- /wp:group -->

<!-- wp:group {"tagName":"section","metadata":{"name":"Signature Tower Experience"},"align":"full","className":"mt-section mt-tw is-style-section-dark","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"},"anchor":"tower"} -->
<section class="wp-block-group alignfull mt-section mt-tw is-style-section-dark" id="tower" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up">Signature Tower Experience</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"is-style-display mt-tw__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading is-style-display mt-tw__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'A moment designed <em>to be remembered.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-tw__stage","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__stage"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-tw__a animate-image-reveal"} -->
<figure class="wp-block-image size-large mt-tw__a animate-image-reveal"><img src="<?php echo esc_url( meteora_asset( 'assets/images/towers/couple-pour.webp' ) ); ?>" alt="<?php echo esc_attr__( 'The couple pour sparkling wine over a coupe tower', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-tw__b animate-image-reveal animate-delay-2"} -->
<figure class="wp-block-image size-large mt-tw__b animate-image-reveal animate-delay-2"><img src="<?php echo esc_url( meteora_asset( 'assets/images/towers/coupe-tower-sunset.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Coupe tower at sunset beneath blossoming trees', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-tw__c animate-image-reveal animate-delay-3"} -->
<figure class="wp-block-image size-large mt-tw__c animate-image-reveal animate-delay-3"><img src="<?php echo esc_url( meteora_asset( 'assets/images/towers/espresso-martini-tower.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Espresso Martini Tower on a black table', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-tw__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__text"><!-- wp:paragraph {"className":"is-style-lead animate-fade-up"} -->
<p class="is-style-lead animate-fade-up"><?php echo esc_html__( 'Coupes or glasses arranged in a cascade and filled live by our staff or by the couple. For the toast, the cake cutting or opening the party: an elegant, captivating and highly photogenic moment.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:group {"className":"mt-tw__list","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__list"><!-- wp:group {"className":"mt-tw__set animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__set animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro mt-tw__group"} -->
<p class="is-style-micro mt-tw__group"><?php echo esc_html__( 'Sparkling Towers', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Classic Celebration Tower — Prosecco</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Italian Elegance Tower — Franciacorta</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Golden Cascade — Champagne</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-tw__set animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__set animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro mt-tw__group"} -->
<p class="is-style-micro mt-tw__group"><?php echo esc_html__( 'Spritz Towers', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Aperol / Campari Spritz Tower</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Hugo Spritz Tower</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-tw__set animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__set animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro mt-tw__group"} -->
<p class="is-style-micro mt-tw__group"><?php echo esc_html__( 'Espresso Martini Tower', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Espresso Martini Tower</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-muted mt-tw__small"} -->
<p class="is-muted mt-tw__small"><?php echo esc_html__( 'Would you like a different tower? Just ask. Available alongside the bar service, or on its own on request.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"className":"mt-cta-row"} -->
<div class="wp-block-buttons mt-cta-row"><!-- wp:button {"className":"is-style-button-light"} -->
<div class="wp-block-button is-style-button-light"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'services', 'tower' ) ); ?>"><?php echo esc_html__( 'Discover the Tower Experience', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link meteora-track-tower_quote"} -->
<div class="wp-block-button is-style-button-text-link meteora-track-tower_quote"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->

<!-- wp:cover {"url":"<?php echo esc_url( meteora_asset( 'assets/images/bars/night-lounge.webp' ) ); ?>","alt":"<?php echo esc_attr__( 'Evening bar', 'meteora' ); ?>","minHeight":52,"minHeightUnit":"rem","gradient":"band-shade","tagName":"section","align":"full","className":"mt-band animate-drift","layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-cover alignfull mt-band animate-drift" style="min-height:52rem"><img class="wp-block-cover__image-background" alt="<?php echo esc_attr__( 'Evening bar', 'meteora' ); ?>" src="<?php echo esc_url( meteora_asset( 'assets/images/bars/night-lounge.webp' ) ); ?>" data-object-fit="cover"/><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim wp-block-cover__gradient-background has-background-gradient has-band-shade-gradient-background"></span><div class="wp-block-cover__inner-container"><!-- wp:heading {"className":"mt-band__title animate-fade-up"} -->
<h2 class="wp-block-heading mt-band__title animate-fade-up"><?php echo wp_kses_post( __( 'Picture the bar <em>at your event.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead mt-band__lead animate-fade-up animate-delay-1"} -->
<p class="is-style-lead mt-band__lead animate-fade-up animate-delay-1"><?php echo esc_html__( 'Tell us the date, the place and the guests. We will reply with a tailored proposal.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"className":"mt-cta-row animate-fade-up animate-delay-2"} -->
<div class="wp-block-buttons mt-cta-row animate-fade-up animate-delay-2"><!-- wp:button {"className":"is-style-button-light has-arrow meteora-track-cocktails_band"} -->
<div class="wp-block-button is-style-button-light has-arrow meteora-track-cocktails_band"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></section>
<!-- /wp:cover -->
