<?php
/**
 * Title: Page — Cookie Policy
 * Slug: meteora/page-cookies
 * Categories: meteora-pages
 * Description: Complete “Cookie Policy” page with real content.
 * Viewport Width: 1440
 * Post Types: page
 * Block Types: core/post-content
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:group {"tagName":"section","metadata":{"name":"Cookie Policy"},"align":"full","className":"mt-section mt-legal","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"62rem"}} -->
<section class="wp-block-group alignfull mt-section mt-legal" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:breadcrumbs {"className":"mt-crumbs"} /-->

<!-- wp:heading {"level":1,"className":"mt-legal__title"} -->
<h1 class="wp-block-heading mt-legal__title"><?php echo esc_html__( 'Cookie Policy', 'meteora' ); ?></h1>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-prose","layout":{"type":"default"}} -->
<div class="wp-block-group mt-prose"><!-- wp:paragraph {"className":"is-style-micro mt-legal__draft"} -->
<p class="is-style-micro mt-legal__draft"><?php echo esc_html__( 'Draft — final legal text to be supplied by the client', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading -->
<h2 class="wp-block-heading"><?php echo esc_html__( 'What cookies are', 'meteora' ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><?php echo esc_html__( 'Small text files the site stores on your device to work or to gather information about how it is used.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading -->
<h2 class="wp-block-heading"><?php echo esc_html__( 'Technical cookies (always active)', 'meteora' ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><?php echo esc_html__( 'The site stores your cookie preferences in the browser (localStorage, key meteora_consent). No consent is required.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading -->
<h2 class="wp-block-heading"><?php echo esc_html__( 'Analytics and marketing cookies (consent only)', 'meteora' ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><?php echo esc_html__( 'If configured, Google Analytics 4 / Google Tag Manager and possibly Meta Pixel are loaded only after your explicit consent. [Detailed list to be completed.]', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading -->
<h2 class="wp-block-heading"><?php echo esc_html__( 'Managing your preferences', 'meteora' ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p><?php echo esc_html__( 'You can change your choices at any time from the “Cookie preferences” link in the footer.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
