<?php
/**
 * Title: Make it yours
 * Slug: meteora/personalisation
 * Categories: meteora-sections
 * Description: Personalisation options with the ice stamp image.
 * Viewport Width: 1440
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:group {"tagName":"section","metadata":{"name":"Make it yours"},"align":"full","className":"mt-section mt-pz is-style-section-alt","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"},"anchor":"personalisation"} -->
<section class="wp-block-group alignfull mt-section mt-pz is-style-section-alt" id="personalisation" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:group {"className":"mt-pz__grid","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pz__grid"><!-- wp:group {"className":"mt-pz__media","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pz__media"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-pz__img animate-image-reveal animate-drift"} -->
<figure class="wp-block-image size-large mt-pz__img animate-image-reveal animate-drift"><img src="<?php echo esc_url( meteora_asset( 'assets/images/details/ice-stamp.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Ice cube pressed with initials beside a brass stamp', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"mt-caption"} -->
<p class="mt-caption"><?php echo esc_html__( 'Initials pressed into ice. The stamp is yours to keep.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-pz__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pz__text"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up"><?php echo esc_html_x( 'Customisation', 'variant 2', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"animate-fade-up animate-delay-1","anchor":"personalisation-title"} -->
<h2 id="personalisation-title" class="wp-block-heading animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'Make it <em>yours.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-style-lead is-muted mt-pz__lead animate-fade-up animate-delay-2"} -->
<p class="is-style-lead is-muted mt-pz__lead animate-fade-up animate-delay-2"><?php echo esc_html__( 'Bespoke details turn the bar service into an experience that reflects the couple, or the brand.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:group {"className":"mt-pz__list","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pz__list"><!-- wp:group {"className":"mt-pz__row animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pz__row animate-fade-up"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Custom napkins', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'With the couple’s names or a company logo.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-micro mt-pz__notice"} -->
<p class="is-style-micro mt-pz__notice"><?php echo esc_html__( '35 days’ notice', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-pz__row animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pz__row animate-fade-up"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Custom bar front', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Names or logo on the counter: the bar becomes a branded focal point.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"is-style-micro mt-pz__notice"} -->
<p class="is-style-micro mt-pz__notice"><?php echo esc_html__( '35 days’ notice', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-pz__row animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pz__row animate-fade-up"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Fruit engraving', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Names or logo etched on decorative fruit. A detail that surprises.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-pz__row animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pz__row animate-fade-up"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Ice engraving', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Logo or names pressed into large ice cubes. At the end of the event the stamp is yours to keep.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-pz__row animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pz__row animate-fade-up"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Bespoke cocktail list', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'Drinks created and named after the couple’s personality or the brand identity.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-pz__row animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-pz__row animate-fade-up"><!-- wp:heading {"level":3} -->
<h3 class="wp-block-heading"><?php echo esc_html__( 'Branded uniforms', 'meteora' ); ?></h3>
<!-- /wp:heading -->

<!-- wp:paragraph {"className":"is-muted"} -->
<p class="is-muted"><?php echo esc_html__( 'For corporate events: logo on shirt, waistcoat and tie with screen-printed patches.', 'meteora' ); ?></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-style-micro mt-pz__foot"} -->
<p class="is-style-micro mt-pz__foot"><?php echo esc_html__( 'Customisations are agreed during the event-planning phase.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"className":"is-style-button-text-link meteora-track-personalisation"} -->
<div class="wp-block-button is-style-button-text-link meteora-track-personalisation"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Let’s talk details', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
