<?php
/**
 * Title: Portfolio — latest events
 * Slug: meteora/portfolio
 * Categories: meteora-sections, query
 * Description: Asymmetric editorial grid of event stories (posts).
 * Viewport Width: 1440
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:group {"tagName":"section","align":"full","className":"mt-section mt-portfolio","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-section mt-portfolio" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:query {"queryId":7,"query":{"perPage":3,"pages":0,"offset":0,"postType":"post","order":"asc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false},"className":"mt-pg","layout":{"type":"default"}} -->
<div class="wp-block-query mt-pg"><!-- wp:post-template {"className":"mt-pg__list","layout":{"type":"default"}} -->
<!-- wp:post-featured-image {"isLink":true,"aspectRatio":"3/2","className":"mt-pg__media hover-zoom"} /-->

<!-- wp:post-terms {"term":"post_tag","separator":" — ","className":"is-style-micro mt-pg__type"} /-->

<!-- wp:post-title {"level":3,"isLink":true,"className":"mt-pg__title"} /-->

<!-- wp:post-excerpt {"showMoreOnNewLine":false,"excerptLength":30,"className":"mt-pg__excerpt"} /-->

<!-- wp:read-more {"content":"<?php echo esc_attr__( 'Read the story', 'meteora' ); ?>","className":"mt-pg__cta"} /-->
<!-- /wp:post-template --></div>
<!-- /wp:query --></section>
<!-- /wp:group -->
