<?php
/**
 * Title: Signature Tower Experience
 * Slug: meteora/tower
 * Categories: meteora-sections
 * Description: Cinematic tower section.
 * Viewport Width: 1440
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:group {"tagName":"section","metadata":{"name":"Signature Tower Experience"},"align":"full","className":"mt-section mt-tw is-style-section-dark","style":{"spacing":{"padding":{"top":"var:preset|spacing|section","bottom":"var:preset|spacing|section"}}},"layout":{"type":"constrained","contentSize":"1440px"},"anchor":"tower"} -->
<section class="wp-block-group alignfull mt-section mt-tw is-style-section-dark" id="tower" style="padding-top:var(--wp--preset--spacing--section);padding-bottom:var(--wp--preset--spacing--section)"><!-- wp:paragraph {"className":"is-style-eyebrow animate-fade-up"} -->
<p class="is-style-eyebrow animate-fade-up">Signature Tower Experience</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"is-style-display mt-tw__title animate-fade-up animate-delay-1"} -->
<h2 class="wp-block-heading is-style-display mt-tw__title animate-fade-up animate-delay-1"><?php echo wp_kses_post( __( 'A moment designed <em>to be remembered.</em>', 'meteora' ) ); ?></h2>
<!-- /wp:heading -->

<!-- wp:group {"className":"mt-tw__stage","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__stage"><!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-tw__a animate-image-reveal"} -->
<figure class="wp-block-image size-large mt-tw__a animate-image-reveal"><img src="<?php echo esc_url( meteora_asset( 'assets/images/towers/couple-pour.webp' ) ); ?>" alt="<?php echo esc_attr__( 'The couple pour sparkling wine over a coupe tower', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-tw__b animate-image-reveal animate-delay-2"} -->
<figure class="wp-block-image size-large mt-tw__b animate-image-reveal animate-delay-2"><img src="<?php echo esc_url( meteora_asset( 'assets/images/towers/coupe-tower-sunset.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Coupe tower at sunset beneath blossoming trees', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:image {"sizeSlug":"large","linkDestination":"none","className":"mt-tw__c animate-image-reveal animate-delay-3"} -->
<figure class="wp-block-image size-large mt-tw__c animate-image-reveal animate-delay-3"><img src="<?php echo esc_url( meteora_asset( 'assets/images/towers/espresso-martini-tower.webp' ) ); ?>" alt="<?php echo esc_attr__( 'Espresso Martini Tower on a black table', 'meteora' ); ?>"/></figure>
<!-- /wp:image -->

<!-- wp:group {"className":"mt-tw__text","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__text"><!-- wp:paragraph {"className":"is-style-lead animate-fade-up"} -->
<p class="is-style-lead animate-fade-up"><?php echo esc_html__( 'Coupes or glasses arranged in a cascade and filled live by our staff or by the couple. For the toast, the cake cutting or opening the party: an elegant, captivating and highly photogenic moment.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:group {"className":"mt-tw__list","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__list"><!-- wp:group {"className":"mt-tw__set animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__set animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro mt-tw__group"} -->
<p class="is-style-micro mt-tw__group"><?php echo esc_html__( 'Sparkling Towers', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Classic Celebration Tower — Prosecco</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Italian Elegance Tower — Franciacorta</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Golden Cascade — Champagne</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-tw__set animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__set animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro mt-tw__group"} -->
<p class="is-style-micro mt-tw__group"><?php echo esc_html__( 'Spritz Towers', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Aperol / Campari Spritz Tower</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Hugo Spritz Tower</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"className":"mt-tw__set animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-tw__set animate-fade-up"><!-- wp:paragraph {"className":"is-style-micro mt-tw__group"} -->
<p class="is-style-micro mt-tw__group"><?php echo esc_html__( 'Espresso Martini Tower', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"className":"mt-tw__item"} -->
<p class="mt-tw__item">Espresso Martini Tower</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:paragraph {"className":"is-muted mt-tw__small"} -->
<p class="is-muted mt-tw__small"><?php echo esc_html__( 'Would you like a different tower? Just ask. Available alongside the bar service, or on its own on request.', 'meteora' ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"className":"mt-cta-row"} -->
<div class="wp-block-buttons mt-cta-row"><!-- wp:button {"className":"is-style-button-light"} -->
<div class="wp-block-button is-style-button-light"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'services', 'tower' ) ); ?>"><?php echo esc_html__( 'Discover the Tower Experience', 'meteora' ); ?></a></div>
<!-- /wp:button -->

<!-- wp:button {"className":"is-style-button-text-link meteora-track-tower_quote"} -->
<div class="wp-block-button is-style-button-text-link meteora-track-tower_quote"><a class="wp-block-button__link wp-element-button" href="<?php echo esc_url( meteora_page_url( 'contact' ) ); ?>"><?php echo esc_html__( 'Request a quote', 'meteora' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->
