<?php
/**
 * Title: Trust — 14+ years
 * Slug: meteora/trust-bar
 * Categories: meteora-sections
 * Description: 14+ years of experience and key differentiators.
 * Viewport Width: 1440
 *
 * Generated by wordpress/tools/build.py — edit the generator or edit the pattern in the Site Editor.
 *
 * @package Meteora
 */

?>
<!-- wp:group {"tagName":"section","metadata":{"name":"Trust bar"},"align":"full","className":"mt-trust","layout":{"type":"constrained","contentSize":"1440px"}} -->
<section class="wp-block-group alignfull mt-trust"><!-- wp:group {"className":"mt-trust__figure animate-fade-up","layout":{"type":"default"}} -->
<div class="wp-block-group mt-trust__figure animate-fade-up"><!-- wp:paragraph {"className":"mt-trust__num"} -->
<p class="mt-trust__num"><?php echo wp_kses_post( __( '14<span>+</span>', 'meteora' ) ); ?></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"className":"is-style-micro mt-trust__label"} -->
<h2 class="wp-block-heading is-style-micro mt-trust__label"><?php echo esc_html__( '14+ years of operational event experience', 'meteora' ); ?></h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:list {"className":"mt-trust__list animate-fade-up animate-delay-2"} -->
<ul class="wp-block-list mt-trust__list animate-fade-up animate-delay-2"><!-- wp:list-item -->
<li><?php echo esc_html__( 'Professional staff', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Independent operation', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Scenographic bars', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Professional glassware', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Curated ice', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Cocktail experience', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Customisation', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Respect for venues', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Discreet hospitality', 'meteora' ); ?></li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li><?php echo esc_html__( 'Italy-wide service', 'meteora' ); ?></li>
<!-- /wp:list-item --></ul>
<!-- /wp:list --></section>
<!-- /wp:group -->
